### ISSUE TITLE
Decide where Cypht's Docker images will live

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#1016]
Cypht's founder (Jason Munro) was publishing Docker images here: https://hub.docker.com/r/sailfrog/cypht-docker

More background info here: https://github.com/cypht-org/cypht-docker/issues/31 but Jason's expertise is not Docker, and this part was not worked on that much. Despite this, we have over 100K+ pulls!
![image](https://github.com/cypht-org/cypht/assets/1004261/68ad7ad6-a5a8-4ce2-9c2b-8d06c9eef6c6)

We have control of this account and Jason is not using for anything else.

Option 1:
* We deprecate https://hub.docker.com/r/sailfrog/cypht-docker and we point everyone to a URL that looks more official
* We need to do some research to see if there is a seamless redirect, or accept any negative impacts on the project (ex.: tons of users need to update their repos, loosing the pull stats, etc.

Option 2:
* We keep https://hub.docker.com/r/sailfrog/cypht-docker as the official source
* We convert it to an organization: https://docs.docker.com/admin/convert-account/
* We document clearly any changes following the major changes: https://github.com/cypht-org/cypht/pull/1001

We are a good candidate for "Docker-Sponsored Open Source program"
https://www.docker.com/community/open-source/application/

Can someone think of an option 3?

On a related note: while the project now lives at https://github.com/cypht-org/cypht instead of https://github.com/jasonmunro/cypht, we opted to not change the packages on Packagist.org. So we have less official-looking URLs:
* https://packagist.org/packages/jason-munro/cypht
* https://packagist.org/packages/henrique-borba/php-sieve-manager

Related discussion: https://github.com/composer/packagist/issues/47

**Comment by jonocodes** [comment]
Docker-Sponsored Open Source program is a great idea

**Comment by marclaporte** [comment]
@rodriguezny @kroky @fabiomontefuscolo please advise.

**Comment by marclaporte** [comment]
> does Tiki have a sponsored account?

yes, managed by @rodriguezny

**Comment by kroky** [comment]
Option 2 sounds good.

**Comment by rodriguezny** [comment]
Option 1 would be good as it can allow to have a URL that looks more official. Instead of its cons, we should pick it.  So, let's pick option 2 due to cons that has option 1.

**Comment by marclaporte** [comment]
https://hub.docker.com/u/cypht will have something to pull soon!

Thank you @jonocodes for your leadership and expertise!

@rodriguezny is working on the application for the Docker-Sponsored Open Source program.
