### ISSUE TITLE
Can't edit local contacts

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1023]
## 🐛 Bugreport
I'm unable to edit or delete local contacts, either from the "Personal Addresses" tab, or the "Collected Recipients" tab.  The button to send a message to a contact works, but the edit and delete buttons have no effect.  The "Automatically add outgoing email addresses" checkbox does work, but it adds duplicates to the "Collected Recipients" list every time you send a message to the same email.

### Version & Environment

Rev: 6d0e50a

### Steps to reproduce
1. Try to edit or delete a local contact.
2. That's it.  It doesn't work.

**Comment by josaphatim** [comment]
@PaulTGG issue fixed here https://github.com/cypht-org/cypht/pull/1028
