### ISSUE TITLE
Allow for renaming account

### ISSUE THREAD

**Issue by jonocodes** [cypht-org/cypht#1035]
## 🗣 Suggestion

I created several gmail/imap accounts. I may want to change the password or rename the account, but on the servers page they seem to be read only.

**Comment by marclaporte** [comment]
This is something that bugged me with Cypht 1.4.x as well... Let's address in 2.0.2 or 2.0.3

@henochit As you revamped this section, any wisdom to share?
https://github.com/cypht-org/cypht/pull/855

Thanks!

**Comment by josaphatim** [comment]
@jonocodes, @marclaporte
I have proposed something in https://github.com/cypht-org/cypht/pull/1074.
I need feedback. Thanks.
