### ISSUE TITLE
Release Cypht 2.1

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#1050]
Please release Cypht 2.1.0
It should include PHPUnit 10 and thus require PHP 8.1+
It will be our first version for our new Docker setup

Please make sure it includes https://github.com/cypht-org/cypht/pull/1044, https://github.com/cypht-org/cypht/pull/1043 and whatever else is ready at https://github.com/cypht-org/cypht/pulls

**Comment by jonocodes** [comment]
The first docker release already happened. Version 2.0.1:
https://github.com/cypht-org/cypht/issues/1047#issuecomment-2134335595

And if version 2.1 is using PHP 8, we will need to update and test the Dockerfile before releasing.

**Comment by marclaporte** [comment]
@josaphatim @Shadow243 @Yannick243  please also address any severe issues from https://github.com/cypht-org/cypht/wiki/Test-IMAP-SMTP-&-JMAP-SMTP-with-Stalwart

**Comment by marclaporte** [comment]
79 commits so far:
https://github.com/cypht-org/cypht/compare/v2.0.1...master

Let's get all these enhancements packaged :-)

**Comment by Shadow243** [comment]
> 79 commits so far:
> 
> https://github.com/cypht-org/cypht/compare/v2.0.1...master
> 
> 
> 
> Let's get all these enhancements packaged :-)

Copy that

**Comment by marclaporte** [comment]
https://github.com/cypht-org/cypht/releases/tag/v2.1.0

**Comment by marclaporte** [comment]
Related: https://github.com/cypht-org/cypht-website/pull/64
