### ISSUE TITLE
Unable to add servers

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1084]
## 🐛 Bugreport

I'm not able to add any servers.  I hadn't updated Cypht in some time, so I don't know which commit may have caused it.  Here's a sample error message.

`[Thu Jun 13 12:02:30.707194 2024] [proxy_fcgi:error] [pid 71080] [client[deleted]] AH01071: Got error 's_dir' => '/var/lib/hm3/users', 'attachment_dir' => '/var/lib/hm3/attachments', 'app_data_dir' => '/var/lib/hm3/app_data', 'disable_origin_check' => TRUE, 'admin_users' => NULL, 'cookie_domain' => NULL, 'cookie_pat...; PHP message: PHP   3. Hm_Request->__construct($filters = ['allowed_output' => ['date' => [...], 'formatted_folder_list' => [...], 'router_user_msgs' => [...], 'router_login_state' => [...], 'formatted_message_list' => [...], 'just_saved_credentials' => [...], 'just_forgot_credentials' => [...], 'deleted_server_id' => [...], 'msg_headers' => [...], 'msg_text' => [...], 'msg_source' => [...], 'msg_parts' => [...], 'page_links' => [...], 'folder_status' => [...], 'imap_server_id' => [...], 'imap_service_name' => [...], 'contact_deleted' => [...], 'imported_contact' => [...], 'contact_suggestions' => [...], 'collect_contacts' => [...], 'imap_allow_images' => [...], 'collected_contact_email' => [...], 'collected_contact_name' => [...], 'imap_connect_status' => [...], 'connect_status' => [...], 'auto_sent_folder' => [...], 'imap_connect_time' => [...], 'imap_detail_display' => [...], 'imap_status_display' => [...], 'imap_status_server_id' => [...], 'imap_expanded_folder_path' => [...], 'imap_expanded_fo...; PHP message: PHP   4. Hm_Request->filter_request_input() /usr/local/share/cypht/lib/request.php:81; PHP message: PHP   5. Hm_Request->filter_input($type = 5, $filters = ['REQUEST_URI' => 516, 'REQUEST_METHOD' => 516, 'SERVER_ADDR' => 275, 'REMOTE_ADDR' => 275, 'SERVER_PORT' => 257, 'SERVER_PROTOCOL' => 516, 'PHP_SELF' => 516, 'REQUEST_SCHEME' => 516, 'HTTP_HOST' => 516, 'HTTP_ORIGIN' => 273, 'HTTP_REFERER' => 273, 'HTTP_ACCEPT_LANGUAGE' => 516, 'HTTP_ACCEPT_ENCODING' => 516, 'HTTP_ACCEPT_CHARSET' => 516, 'HTTP_ACCEPT' => 516, 'HTTP_USER_AGENT' => 516, 'HTTPS' => 516, 'SERVER_NAME' => 516, 'HTTP_X_REQUESTED_WITH' => 516, 'HTTP_X_FORWARDED_HOST' => 516]) /usr/local/share/cypht/lib/request.php:100; PHP message: PHP   6. Hm_Functions::filter_input_array($type = 5, $filters = ['REQUEST_URI' => 516, 'REQUEST_METHOD' => 516, 'SERVER_ADDR' => 275, 'REMOTE_ADDR' => 275, 'SERVER_PORT' => 257, 'SERVER_PROTOCOL' => 516, 'PHP_SELF' => 516, 'REQUEST_SCHEME' => 516, 'HTTP_HOST' => 516, 'HTTP_ORIGIN' => 273, 'HTTP_REFERER' => 273, 'HTTP_ACCEPT_LANGUAGE' => 516, 'HTTP_ACCEPT_ENCODING' => 516, 'HTTP_ACCEPT_CHARSET' => 516, 'HTTP_ACCEPT' => 516, 'HTTP_USER_AGENT' => 516, 'HTTPS' => 516, 'SERVER_NAME' => 516, 'HTTP_X_REQUESTED_WITH' => 516, 'HTTP_X_FORWARDED_HOST' => 516]) /usr/local/share/cypht/lib/request.php:167; PHP message: PHP Warning:  Undefined array key "HTTP_X_FORWARDED_HOST" in /usr/local/share/cypht/lib/framework.php on line 213; PHP message: PHP Stack trace:; PHP message: PHP   1. {main}() /usr/local/share/cypht/site/index.php:0; PHP message: PHP   2. Hm_Dispatch->__construct($config = class Hm_Site_Config_File { protected $source = ''; protected $config = ['version' => 0.1, '2fa_secret' => '[deleted]', '2fa_simple' => FALSE, 'session_type' => 'DB', 'auth_type' => 'DB', 'ldap_auth_server' => 'localhost', 'ldap_auth_port' => '389', 'ldap_auth_tls' => NULL, 'ldap_auth_base_dn' => 'example,dc=com', 'imap_auth_name' => 'localhost', 'imap_auth_server' => 'localhost', 'imap_auth_port' => '143', 'imap_auth_tls' => TRUE, 'imap_auth_sieve_conf_host' => 'tls://mail.gandi.net:4190', 'default_smtp_name' => NULL, 'default_smtp_server' => NULL, 'default_smtp_port' => NULL, 'default_smtp_tls' => NULL, 'default_smtp_no_auth' => NULL, 'user_config_type' => 'DB', 'user_settings_dir' => '/var/lib/hm3/users', 'attachment_dir' => '/var/lib/hm3/attachments', 'app_data_dir' => '/var/lib/hm3/app_data', 'disable_origin_check' => TRUE, 'admin_users' => NULL, 'cookie_domain' => NULL, 'cookie_pat...; PHP message: PHP   3. Hm_Request->__construct($filters = ['allowed_output' => ['date' => [...], 'formatted_folder_list' => [...], 'router_user_msgs' => [...], 'router_login_state' => [...], 'formatted_message_list' => [...], 'just_saved_credentials' => [...], 'just_forgot_credentials' => [...], 'deleted_server_id' => [...], 'msg_headers' => [...], 'msg_text' => [...], 'msg_source' => [...], 'msg_parts' => [...], 'page_links' => [...], 'folder_status' => [...], 'imap_server_id' => [...], 'imap_service_name' => [...], 'contact_deleted' => [...], 'imported_contact' => [...], 'contact_suggestions' => [...], 'collect_contacts' => [...], 'imap_allow_images' => [...], 'collected_contact_email' => [...], 'collected_contact_name' => [...], 'imap_connect_status' => [...], 'connect_status' => [...], 'auto_sent_folder' => [...], 'imap_connect_time' => [...], 'imap_detail_display' => [...], 'imap_status_display' => [...], 'imap_status_server_id' => [...], 'imap_expanded_folder_path' => [...], 'imap_expanded_fo...; PHP message: PHP   4. Hm_Request->filter_request_input() /usr/local/share/cypht/lib/request.php:81; PHP message: PHP   5. Hm_Request->filter_input($type = 5, $filters = ['REQUEST_URI' => 516, 'REQUEST_METHOD' => 516, 'SERVER_ADDR' => 275, 'REMOTE_ADDR' => 275, 'SERVER_PORT' => 257, 'SERVER_PROTOCOL' => 516, 'PHP_SELF' => 516, 'REQUEST_SCHEME' => 516, 'HTTP_HOST' => 516, 'HTTP_ORIGIN' => 273, 'HTTP_REFERER' => 273, 'HTTP_ACCEPT_LANGUAGE' => 516, 'HTTP_ACCEPT_ENCODING' => 516, 'HTTP_ACCEPT_CHARSET' => 516, 'HTTP_ACCEPT' => 516, 'HTTP_USER_AGENT' => 516, 'HTTPS' => 516, 'SERVER_NAME' => 516, 'HTTP_X_REQUESTED_WITH' => 516, 'HTTP_X_FORWARDED_HOST' => 516]) /usr/local/share/cypht/lib/request.php:100; PHP message: PHP   6. Hm_Functions::filter_input_array($type = 5, $filters = ['REQUEST_URI' => 516, 'REQUEST_METHOD' => 516, 'SERVER_ADDR' => 275, 'REMOTE_ADDR' => 275, 'SERVER_PORT' => 257, 'SERVER_PROTOCOL' => 516, 'PHP_SELF' => 516, 'REQUEST_SCHEME' => 516, 'HTTP_HOST' => 516, 'HTTP_ORIGIN' => 273, 'HTTP_REFERER' => 273, 'HTTP_ACCEPT_LANGUAGE' => 516, 'HTTP_ACCEPT_ENCODING' => 516, 'HTTP_ACCEPT_CHARSET' => 516, 'HTTP_ACCEPT' => 516, 'HTTP_USER_AGENT' => 516, 'HTTPS' => 516, 'SERVER_NAME' => 516, 'HTTP_X_REQUESTED_WITH' => 516, 'HTTP_X_FORWARDED_HOST' => 516]) /usr/local/share/cypht/lib/request.php:167'`

### Version & Environment

Rev: d7df56d

OS:  []

### Steps to reproduce
1. Install some fresh Cypht on a fresh Debian server
2. Log in and try to add a server.

**Comment by PaulTGG** [comment]
It looks like it stopped working sometime after f77473b was merged.  It was broken in cdeee04, and the only two commits between those two were 71b1266 and c54497f.

**Comment by josaphatim** [comment]
Sorry I accidentally modified the comment. I think https://github.com/cypht-org/cypht/pull/1082 should solve the issue. There is fatal error thrown in hm-imap.php for now.

**Comment by PaulTGG** [comment]
@josaphatim Yep, definitely fixed in #1082, thanks!
