### ISSUE TITLE
Unable to connect to database when running setup_database script

### ISSUE THREAD

**Issue by Yannick243** [cypht-org/cypht#1089]
## 🐛 Bugreport
When trying to set up the necessary tables to manage users, sessions, or settings (hm_user, hm_user_session, hm_user_settings) by running the script `php ./scripts/setup_database.php`, the system is using the default config values and not loading values from the `.env` file. 
The error received is (**Unable to connect to database**) after multiple attempts.

### Steps to reproduce
1. Create an empty database
2. setup the necessary variables in your `.env` file 
(DB_DRIVER, DB_HOST, DB_NAME, DB_USER, DB_PASS, AUTH_TYPE=DB or SESSION_TYPE=DB)
3. Try to generate the related tables by running `php ./scripts/setup_database.php`
4. You will get the error described above

**Comment by josaphatim** [comment]
Close as fixed in https://github.com/cypht-org/cypht/pull/1090
