### ISSUE TITLE
Activating Sieve should be easier

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#1105]
As of now, activating Sieve is more complicated than in should be: https://github.com/cypht-org/cypht-website/pull/67/files

By default, Sieve should be available in a standard Cypht installation. Just activate with 1 checkbox.

**Comment by Baraka24** [comment]
> Hey guys, has this feature been implemented already?

Hey, for a fresh installation of Cypht, you wil have to:
1. go to settings
2. Site
3. General
4. Check Enable sieve filter
Enjoy filters in Cypht.
