### ISSUE TITLE
Themes css path incorrect in Tiki-Cypht integration

### ISSUE THREAD

**Issue by kroky** [cypht-org/cypht#1147]
The link `return '<link href="' . WEB_ROOT . 'modules/themes/assets/' . $theme_name . '/css/' . $theme_name . '.css?v=' . CACHE_ID . '" media="all" rel="stylesheet" type="text/css" />';` in themes/modules work in standalone cypht but not in Tiki-Cypht integration. I think we should change the way this is inserted/requested and do it through config_gen file much like site.css, etc. are generated and included. Then, Tiki-Cypht integration will be able to use the correct path to include the file.

**Comment by marclaporte** [comment]
https://gitlab.com/tikiwiki/tiki/-/merge_requests/5483

**Comment by GedeonTS** [comment]
Fixed by @Shadow243 in https://github.com/cypht-org/cypht/pull/1185
