### ISSUE TITLE
"All" inbox is blank, need help

### ISSUE THREAD

**Issue by europacafe** [cypht-org/cypht#1149]
## 💬 Question
I added two accounts (same domain) without a problem. I can see each inbox mails. When creating those accounts, I did not check the "Hide From Combined Pages". However, when I click "All", no combined inbox mails are displayed.

![image](https://github.com/user-attachments/assets/8bde272f-7560-49ba-a7fa-38c5a02c009d)
![image](https://github.com/user-attachments/assets/a08feea9-c533-48a1-bea9-e3ae982530ce)

**Comment by europacafe** [comment]
Thanks. I definitely have a lot of mails during the last 7 days. I even test sending a few new mails,
![image](https://github.com/user-attachments/assets/7847a19b-4e57-431e-8913-ca6b0f70af26)
![image](https://github.com/user-attachments/assets/5585824b-fcde-43e4-b93a-20bed8dab18a)

**Comment by marclaporte** [comment]
Thank you @europacafe 

Which version number of Cypht?
Manual install? via Docker? via Yunohost? via Tiki?

Can you join us on https://gitter.im/cypht-org/community ?  We could do a screenshare session with one of the developers to pinpoint the cause.

We did a lot of massive changes for Cypht 2.0.0, make Cypht more feature-rich and easier to maintain/evolve. But we broke a few thing in the transition, and we are eager to clean them up :-)

**Comment by marclaporte** [comment]
It's great that you are running Stalwart! Stalwart offers JMAP support, and Cypht now supports JMAP:
https://github.com/cypht-org/cypht/issues/180

And we are now working on Sieve-JMAP: https://github.com/cypht-org/cypht/issues/931

**Comment by europacafe** [comment]
With docker image v2.2.0, this issue has been solved.
Thank you very much
