### ISSUE TITLE
Some HTML messages can't be closed (was "Inline message", where is the setting?)

### ISSUE THREAD

**Issue by europacafe** [cypht-org/cypht#1155]
Cypht 2.1.0 docker (using Stalwart mail server docker)

From the Inline Message module readme, I went to the Site/General setting page, but I did not see its setting parameter. I've checked the modules folder, it is there.
![image](https://github.com/user-attachments/assets/b0d3fee0-b909-4a96-aee5-ba1cb5161797)

**even I manually edit the env file to turn it to "true", it didn't show inline message**
![image](https://github.com/user-attachments/assets/30dc1bcc-b532-4808-b036-5736e752ead4)

![image](https://github.com/user-attachments/assets/352a65d8-9c37-433b-a983-8e7335dc457e)

![image](https://github.com/user-attachments/assets/d4365254-5eae-4501-8bd4-98b1d0a2f027)

**Comment by marclaporte** [comment]
@christer77 Please figure this out.

**Comment by christer77** [comment]
> **even I manually edit the env file to turn it to "true", it didn't show inline message**

Hello @europacafe,

Among the list of modules present in the environment variable **_CYPHT_MODULES_** in .env file; Can you confirm that you have _**inline_message**_ in this list?

**Comment by europacafe** [comment]
thank you very much. You are right. After adding it in the env file, it is working now.

**Comment by europacafe** [comment]
One more thing. Most inline messages work great, they have an 'x' button on the upper right for closing the expanded message. However, some html messages don't have such 'x' icon; thus can't close.
![image](https://github.com/user-attachments/assets/33940ab4-4b69-4f4c-a359-3e3898f148b1)

**Comment by christer77** [comment]
> One more thing. Most inline messages work great, they have an 'x' button on the upper right for closing the expanded message. However, some html messages don't have such 'x' icon; thus can't close; even I scrolled horizontally to the right-most part of the html page. ![image](https://private-user-images.githubusercontent.com/51871976/356932424-33940ab4-4b69-4f4c-a359-3e3898f148b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTIxNDUsIm5iZiI6MTcyMzQ5MTg0NSwicGF0aCI6Ii81MTg3MTk3Ni8zNTY5MzI0MjQtMzM5NDBhYjQtNGI2OS00ZjRjLWEzNTktM2UzODk4ZjE0OGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE5NDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMjNkOGE4ZThhODNhMmJmYTdmNmQ1MzVjZjhjMTg0ZTIwNzExMTZhMzhkOTk3NTIyOWM5Zjc5NWIyM2IyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YIl21VfW7-zMex5pjXXHZCdFSmRBsSEMU3QUtS9MUEo)

We tried to reproduce the issue, you're right, now we're going to do it

**Comment by Shadow243** [comment]
@europacafe can you confirm on your side after this PR: [https://github.com/cypht-org/cypht/pull/1172](https://github.com/cypht-org/cypht/pull/1172)

**Comment by europacafe** [comment]
> @europacafe can you confirm on your side after this PR: #1172 please!
Thanks for the fix. I believe you fix it on the master code; but I'm running v.2.1.0, not the master. 

For the modules/imap/site.js file, when I opened it for manual amendment/fix, line 837 is not the same as yours, so I believe it is not the same version as yours before the fix.

I rather wait till the official release upgrade.
