### ISSUE TITLE
REDIRECT_AFTER_LOGIN works only on desktop, but not mobile Chrome and Edge

### ISSUE THREAD

**Issue by europacafe** [cypht-org/cypht#1160]
## 🐛 Bugreport
I've set the REDIRECT_AFTER_LOGIN to redirect to one of my INBOX accounts, after login. It works fine with the Microsoft Edge browser on my desktop; but not on my phone Microsoft Edge and Chrome
### Version & Environment
cypht 2.1.0, mailserver: stalwart

OS (phone):  Xiaomi Mi10T Pro, MIUI version: MIUI Global 14.0.1, Android version: (see screenshot below)
![image](https://github.com/user-attachments/assets/43c492be-19dc-436e-a119-3b75c9667c50)

environment file setup: 
![image](https://github.com/user-attachments/assets/0ffef105-7017-432f-a709-7100092514ee)

after login with Microsoft Edge on Windows 11, it works as expected
![image](https://github.com/user-attachments/assets/e8a52c51-4ad0-495c-8038-07e2299162ee)

after login with Microsoft Edge (version: 127.0.2651.90) on my phone
![image](https://github.com/user-attachments/assets/4a096f5d-1e0a-44f3-bc08-3c10bc68c1c1)

after login with Chrome (version: 127.0.6533.103) on my phone
![image](https://github.com/user-attachments/assets/924b3b1f-fea2-41c1-859f-a5564dac1046)

after login with Microsoft Edge or Chrome on my phone, in private mode (**incognito mode**), it displays Cypht welcome page, with "offline" status. I can't make screenshots when in incognito mode.

**Comment by europacafe** [comment]
with docker image v2.1.0 and 2.2.0, this is the same issue as reported at [[](url)](https://github.com/cypht-org/cypht/issues/1173)

**Comment by marclaporte** [comment]
@europacafe Please check 2.3.0

**Comment by europacafe** [comment]
Thks. Confirm working, except the broken theme
