### ISSUE TITLE
Emails can't be moved to a new location anymore via drag and drop

### ISSUE THREAD

**Issue by jacob-js** [cypht-org/cypht#1165]
Seen on the latest master, holding a message via the messages list and moving it around in an attempt to drop it into a new folder does not do anything.
Maybe some code from https://github.com/cypht-org/cypht/pull/834 has been displaced?

**Comment by marclaporte** [comment]
Thank you @jacob-js for the report. This is a good one for @GedeonTS to explore Cypht code :-)
