### ISSUE TITLE
Safari browser on iPad and MS Edge on Android give wrong inbox display

### ISSUE THREAD

**Issue by europacafe** [cypht-org/cypht#1173]
## 🐛 Bugreport
I set Cypht to go direct to display one of my inbox after login. Chrome can display it correctly, but Safari can’t render the display correctly and no messages list was displayed.

### Version & Environment
Cypht 2.1.0 runs as a container

on iPad Safari browser and MS Edge on Android gave similar result (Chrome on Android is ok)
![image](https://github.com/user-attachments/assets/4acae60b-bb69-4e6d-80d9-4b2175487515)
![image](https://github.com/user-attachments/assets/df1aab0b-0ada-458b-bb90-108d7cde1950)

on Chrome browser
![image](https://github.com/user-attachments/assets/60c033c9-f8cb-4d86-8f2e-8d8af98a4d24)

**Comment by europacafe** [comment]
With docker image 2.2.0, this is still an issue.

**Comment by marclaporte** [comment]
@europacafe and 2.3.0?

**Comment by europacafe** [comment]
Thks. Confirm working, except the broken theme
