### ISSUE TITLE
Cypht menus, buttons, etc., showing codes instead of characters. 

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1174]
## 🐛 Bugreport
The latest code as of this moment is showing those weird entity code squares instead of characters in a bunch of places.  Here's an example.

![Screenshot_2024-08-14_19-18-27](https://github.com/user-attachments/assets/a92f7079-3873-4f64-84ad-16b331d904f1)

### Version & Environment

Rev: 8b0ed3a

### Steps to reproduce
1. Log in to Cypht.
2. goto 1

**Comment by marclaporte** [comment]
Thank you @PaulTGG !

**Comment by nptrainor** [comment]
Plus 1 - I have the same issue. Followed install instructions and get codes rather than icons.

**Comment by marclaporte** [comment]
@nptrainor @PaulTGG Can you try https://github.com/cypht-org/cypht/releases/tag/v2.2.0 ?

**Comment by PaulTGG** [comment]
> @nptrainor @PaulTGG Can you try https://github.com/cypht-org/cypht/releases/tag/v2.2.0 ?

I thought rev 8b0ed3a = 2.2.0?  Would there be any differences?

**Comment by Shadow243** [comment]
I'm trying to reproduce to see if I can find an other scenario

**Comment by PaulTGG** [comment]
> We had the same issue with @kambereBr, We had to run the command: composer install

Just confirming that I ran `composer install` when I upgraded Cypht.  (My use-case is that I keep my settings in a database, but I delete and replace the entire front-end when I update my version.  I don't "update in place.")

**Comment by Shadow243** [comment]
> > We had the same issue with @kambereBr, We had to run the command: composer install
> 
> Just confirming that I ran `composer install` when I upgraded Cypht. (My use-case is that I keep my settings in a database, but I delete and replace the entire front-end when I update my version. I don't "update in place.")

Copy that @PaulTGG , We are looking for the solution, thanks for the feedback.

**Comment by nptrainor** [comment]
After further investigation, it seems that

- bootstrap-icons.woff
- - bootstrap-icons.woff2

did not make their way to the Cypht top level 'fonts' directory on the web server

From my point of view, this problem is solved, but it may continue to affect others too who have not read this report.

**Comment by PaulTGG** [comment]
> After further investigation, it seems that
> 
>     * bootstrap-icons.woff
> 
>     * * bootstrap-icons.woff2
> 
> 
> did not make their way to the Cypht top level 'fonts' directory on the web server
> 
> From my point of view, this problem is solved, but it may continue to affect others too who have not read this report.
> 
> Thank you for all your hard work.

At what point during installation should those files be copied into that directory?  I just tried again with 652e144, and those files were not moved from their subfolders deep in the "vendors" folder.  It seems to me as though there's either some sort of glitch, or the installation instructions need to be updated.

**Comment by europacafe** [comment]
> After further investigation, it seems that
> 
> * bootstrap-icons.woff
> * * bootstrap-icons.woff2
> 
> did not make their way to the Cypht top level 'fonts' directory on the web server
> 
> From my point of view, this problem is solved, but it may continue to affect others too who have not read this report.
> 
> Thank you for all your hard work.

Could you share where can I find those fonts files? I want to manually copy it to my docker image while I'm waiting for the new version release.

**Comment by indridieinarsson** [comment]
I encountered this as well, using the docker image (build with the Dockerfile in the source tree).
There seems to be a glitch in the config_gen.php file. Not sure if this perhaps only affects install via the docker image.
In any case, this diff seems to fix the issue for me:
```
diff --git a/scripts/config_gen.php b/scripts/config_gen.php
index 20e78c6f..5531bebf 100644
--- a/scripts/config_gen.php
+++ b/scripts/config_gen.php
@@ -307,8 +307,9 @@ function append_bootstrap_icons_files() {
     if (!is_dir("site/fonts")) {
         mkdir('site/fonts', 0755);
     }
-    $source_folder = 'vendor/twbs/bootstrap-icons/font/fonts/';
-    $files = glob(VENDOR_PATH . "$source_folder*.*");
+    $source_folder = VENDOR_PATH.'twbs/bootstrap-icons/font/fonts/';
+    $files = glob("$source_folder*.*");
     foreach($files as $file){
         $dest_forlder = str_replace($source_folder, "site/fonts/", $file);
         copy($file, $dest_forlder);
```

**Comment by europacafe** [comment]
@indridieinarsson Thanks for finding out the cause of issue. 

As I don't know how to rebuild a docker image, but I have tried copying those two woff/woff2 files from the `vendor/twbs/bootstrap-icons/font/fonts` folder to the existing `site/fonts` folder; change my docker-compose to make the site/fonts folder persistent, then docker-compose down and up my cypht. The webpage still doesn't display icons.

Any additional things I need to do to make this workaround solution work?
