### ISSUE TITLE
Cypht displays rectangles instead of icons

### ISSUE THREAD

**Issue by europacafe** [cypht-org/cypht#1186]
After upgrading from 2.1.0 to 2.2.0, all the icons are shown as rectangles.

### Version & Environment
Cypht 2.2.0 docker image
Windows 11, Microsoft Edge Version 127.0.2651.105
![image](https://github.com/user-attachments/assets/f565891b-8ead-4ec0-a637-f7772bcad624)

**Comment by marclaporte** [comment]
Thank you. We are discussing here: https://github.com/cypht-org/cypht/issues/1174

**Comment by europacafe** [comment]
Before you release a new docker image version that has solved this problem, what could be the workaround I could make by myself, e.g. to copy fonts to a certain directory?
