### ISSUE TITLE
docker v2.3.0: Is this supposed to be a new UI?

### ISSUE THREAD

**Issue by europacafe** [cypht-org/cypht#1212]
Thanks for quickly updating Cypht to 2.3.0 for both native and docker releases.

I'm not sure the new UI I got after login is supposed to be like this?
![image](https://github.com/user-attachments/assets/42f5eec1-2d68-4ed2-ba2b-439846884ddb)

**Comment by marclaporte** [comment]
Looks broken

**Comment by Shadow243** [comment]
The issue is coming from ASSETS_THEMES_ROOT that is changing only in Tiki.

**Comment by marclaporte** [comment]
Already reported at https://github.com/cypht-org/cypht/issues/1194

Proposed fix: https://github.com/cypht-org/cypht/pull/1214
