### ISSUE TITLE
Can't send emails in 3019c66

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1216]
## 🐛 Bugreport
Clicking the send button on the compose screen doesn't send the email.  (It appears that the email is saved on the server as a draft, but the message isn't actually sent.)

### Version & Environment

Rev: 3019c66

### Steps to reproduce
1. Install Cypht.
2. Compose an email.
3. Hit the Send button.

**Comment by marclaporte** [comment]
Reportedly fixed by https://github.com/cypht-org/cypht/pull/1219
