### ISSUE TITLE
CSS load failed

### ISSUE THREAD

**Issue by catfishlty** [cypht-org/cypht#1221]
### Version & Environment

Rev: Docker Image: cypht/cypht:2.3.0

OS:  Docker Image: cypht/cypht:2.3.0

### Steps to reproduce
1. docker compose up
2. Login account
3. See the website is abnormal.

#### Logs from Chrome Debug Tools
```
Refused to apply style from 'https://mydomain/usr/local/share/cypht/site/modules/themes/assets/default/css/default.css?v=w3PTSESj8Vcr7XTCqz9ck3tpAewcgUkacPMcRWBlgf4%3D' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

#### Screenshot
![1725429974](https://github.com/user-attachments/assets/22acfed2-1472-4322-96ed-f793a00237ae)

**Comment by marclaporte** [comment]
Thank you for the report. We are tracking here: https://github.com/cypht-org/cypht/issues/1194
