### ISSUE TITLE
Stay alert to other potential regressions which arrived in Cypht 2.2.0 related to Unicode Support (Replace Standard PHP String Functions with Multibyte Counterparts)

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#1224]
https://github.com/cypht-org/cypht/pull/1217 by @indridieinarsson
is a partial revert in 2 of the 57 files changed in https://github.com/cypht-org/cypht/pull/1051 by @kambereBr

There could be others, so let's stay alert.

@jasonmunro Can you think of places we should specifically be careful about?

**Comment by indridieinarsson** [comment]
Some tips on this here:
https://stackoverflow.com/questions/10360764/there-are-simple-way-to-get-a-character-from-multibyte-string-in-php
and here :
https://stackoverflow.com/questions/3666306/how-to-iterate-utf-8-string-in-php

**Comment by marclaporte** [comment]
Some work is happening: https://github.com/cypht-org/cypht/pull/1230

**Comment by marclaporte** [comment]
All the related reported regressions have been solved, so closing this.
