### ISSUE TITLE
Can't perform actions on emails selected with checkboxes.

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1287]
## 🐛 Bugreport
Using the checkboxes to select emails, then perform actions on the selected emails, doesn't actually perform the action on the selected emails.

### Version & Environment

Rev: 296b44d

OS:  []

### Steps to reproduce
1. Use a checkbox to select one or more emails (either in the unified inbox, or anywhere else).
2. Use the buttons that appear at the top of the screen to try to perform any action (mark read/unread, delete, archive, etc.)
3. The page updates without reloading, but the action isn't actually performed.

**Comment by marclaporte** [comment]
Here is a recent big change to watch out for: https://github.com/cypht-org/cypht/pull/1266

**Comment by PaulTGG** [comment]
#1266 - Also worth noting that the page's HTML title also stays on the subject of the last opened email, even if the email has been deleted.

**Comment by jacob-js** [comment]
Good catch! https://github.com/cypht-org/cypht/pull/1288 will fix.
