### ISSUE TITLE
DEFAULT_SETTING_TEXT_ONLY's comment & default value are inconsistent

### ISSUE THREAD

**Issue by Denperidge** [cypht-org/cypht#1315]
## 🐛 Bugreport
In the [current version of app.php (line 1026)](https://github.com/cypht-org/cypht/blob/abdd8aab4284967bf676a3f8fdbc37c793120f51/config/app.php#L1026), the comment includes "Defaults to false", while the php env default is set to true

### Version & Environment
Rev: [abdd8aab4284967bf676a3f8fdbc37c793120f51]

**Comment by marclaporte** [comment]
@Denperidge Thank you for the reports (this and the other one). I suggest you make merge requests for things like this, and you will be listed as a contributor of Cypht 2.5.0!

**Comment by Denperidge** [comment]
@marclaporte  Much appreciated! Could you (or someone else with more experience developing Cypht than me) advise on what the correct default value is? (Both for the value in app.php and .env.example? Although with the latter I assume the false value is the correct one)

**Comment by marclaporte** [comment]
@Denperidge Please confirm in latest master

**Comment by Denperidge** [comment]
Looks perfect! Closing issue 😌
