### ISSUE TITLE
how do i manage users?

### ISSUE THREAD

**Issue by jenny787** [cypht-org/cypht#1328]
## 💬 Question

I have installed cypht using the docker image.  I have the one user defined in the docker compose file.  But how do I add and manage additional users?  Thanks.

**Comment by IrAlfred** [comment]
Yes, of course. Try this :
1. Open the terminal session in the running Docker container using 
`docker exec -it <container_name> /bin/sh`
3. Next create another user with the following command 
`php ./scripts/create_account.php username password`

**Comment by jenny787** [comment]
yes, thank you for the quick response.  That works very well!

I read about an "Accounts" section in the GUI where this can be managed, but I don't see it in my interface.  Is there a way to get that to show?  Thank you.

**Comment by IrAlfred** [comment]
This feature is not currently implemented in the GUI, but from the CLI, you can add or delete a user account.

**Comment by jenny787** [comment]
Thank you, I appreciate your prompt help.
