### ISSUE TITLE
HTML composer is missing.

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1349]
## 🐛 Bugreport
The compose page is defaulting to plain text emails, with no way to write a HTML message.  This is causing an issue where replying to rich text/HTML emails adds all the email markup to the reply.  The screenshot is showing my compose page, with HTML selected as the outbound mail format.

![compose](https://github.com/user-attachments/assets/c329fc38-d683-4bde-8e38-9906cca6b129)

### Version & Environment

Rev: 02182bb

OS:  []

### Steps to reproduce
1. Install latest Cypht.
2. Change outbound mail format setting to "HTML"
3. Compose an email.

**Comment by marclaporte** [comment]
Related: https://github.com/cypht-org/cypht/issues/1136

**Comment by jacob-js** [comment]
Fixed by: https://github.com/cypht-org/cypht/pull/1372
