### ISSUE TITLE
Cypht marking all emails as read

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1350]
## 🐛 Bugreport
The latest Cypht is marking all messages per account as being read, if you open an email (not inline), and perform an action on it (such as delete).

### Version & Environment

Rev: 02182bb

OS:  []

### Steps to reproduce
1. Install Cypht
2. Open an email with an account that has some unread messages in it.
3. Delete the email.  The other messages in that accounts inbox will be marked as read.

**Comment by PaulTGG** [comment]
More info: I just noticed that reading one email marks all the other emails in that account as being read.  No specific action required in the test I just did.

**Comment by christer77** [comment]
Thanks for this.

I'm getting started

**Comment by christer77** [comment]
Hello @PaulTGG 

I must say that I tested both cases, but I can't reproduce issue. In short, unread messages remain as such.

**Comment by PaulTGG** [comment]
Hi @christer77, I just tried again, with a fresh Debian install, and a fresh install of the latest Cypht master.  As soon as I opened one email (in this case, it was not inline), and went back to my combined inbox, all the other emails for that account were marked as read.  (I confirmed this with a separate email app.)

**Comment by marclaporte** [comment]
@PaulTGG @christer77 please coordinate a screenshare on https://gitter.im/cypht-org/community

**Comment by christer77** [comment]
Hi @PaulTGG,

Can you confirm [this](https://github.com/cypht-org/cypht/pull/1376)

**Comment by PaulTGG** [comment]
@christer77 Looks good to me, thanks!
