### ISSUE TITLE
Display Image not working

### ISSUE THREAD

**Issue by ulfgebhardt** [cypht-org/cypht#1367]
## 🐛 Bugreport

Display Image not working

![image](https://github.com/user-attachments/assets/37367b84-d82d-42c0-a669-c2a52958b569)

In an email with an image clicking on `image/jpeg` does not open the image as it used to be, but redirects to the main page.

Possibly related: #1355 

### Mitigation

The `Download` button works

### Expected behaviour

The contents of the mail should be replaced with the image, showing the image in its original size

### Version & Environment

Rev: [v2.4.0]

OS:  [chromium, alpine]

### Steps to reproduce
1. Open Mail with Image
2. Click on `image/jpeg`
3. Be redirected to `/?page=message_list&list_path=combined_inbox`
4. ...
5. Profit

**Comment by jacob-js** [comment]
Fixed in commit: https://github.com/cypht-org/cypht/pull/1288/commits/4b536d1f53922818c820b2d460127ef83267a0ab
