### ISSUE TITLE
Move button without functionality in 50% of the cases

### ISSUE THREAD

**Issue by ulfgebhardt** [cypht-org/cypht#1368]
## 🐛 Bugreport

Move button without functionality in 50% of the cases

It happens very often, when selecting an email the move button is correctly shown, but has no functionality. This seems to be click handler register issue.

![image](https://github.com/user-attachments/assets/70654239-af2c-41ac-95be-2f65412ec13c)

### Version & Environment

Rev: [v2.4.0]

OS:  [chromium, alpine]

### Steps to reproduce
1. Mark Mail
2. Click Move Button
3. Nothing happens in ~25-50% of the cases
4. ...
5. Profit

**Comment by jacob-js** [comment]
The move button works perfectly fine. @ulfgebhardt could you please share the details of your device and/or browser?

**Comment by ulfgebhardt** [comment]
![image](https://github.com/user-attachments/assets/167a03b0-cefb-429f-a3a7-57fdc4c00445)

**Comment by ulfgebhardt** [comment]
Further debug info:

If this happens the classes of the move button (an `<a>`) do not change.

1. No message selected (invisible): `imap_move btn btn-sm btn-secondary no_mobile disabled_input`
2. Selecting a message (clickable): `imap_move btn btn-sm btn-secondary no_mobile`
3. Deselecting the message (invisible): `imap_move btn btn-sm btn-secondary no_mobile disabled_input`

Error case:
1. No message selected (invisible): `imap_move btn btn-sm btn-secondary no_mobile disabled_input`
2. Selecting a message (unclickable): `imap_move btn btn-sm btn-secondary no_mobile disabled_input`
3. Deselecting the message (invisible): `imap_move btn btn-sm btn-secondary no_mobile disabled_input`

Removing the class `disabled_input` manually does not make the button clickable

**Comment by jacob-js** [comment]
Let's try to solve this. Please share with me the value of the id attribute for the checked box of a message.

**Comment by ulfgebhardt** [comment]
``` 
<td class="checkbox_cell"><input id="imap_6738e4f407104_5130_494e424f58" type="checkbox" value="imap_6738e4f407104_5130_494e424f58"><label class="checkbox_label" for="imap_6738e4f407104_5130_494e424f58"></label></td>
```

**Comment by jacob-js** [comment]
@IrAlfred @Baraka24 Please try and see if this issue is reproducible. Thanks!

**Comment by mercihabam** [comment]
@Baraka24 @IrAlfred, could you please provide your feedback? Did you follow the steps detailed by @ulfgebhardt and reproduce the issue?

**Comment by Baraka24** [comment]
Everything works my side too, see from:
<img width="947" alt="Cypht2 4 0_moveEmail" src="https://github.com/user-attachments/assets/a2af7471-0901-4bfa-bd31-e76be9d58095">

About Chromium
```
Chromium
Version 133.0.6861.0 (Developer Build) (64-bit)
```

**Comment by marclaporte** [comment]
@ulfgebhardt Maybe you can do a screenshare with one of the devs?

All devs are here: https://gitter.im/cypht-org/community

**Comment by ulfgebhardt** [comment]
> @ulfgebhardt Maybe you can do a screenshare with one of the devs?
> 
> All devs are here: https://gitter.im/cypht-org/community

I did a pairing with @Baraka24 and showed him how to reproduce on my end - lets see if he can reproduce it.

If there is no result I say, lets close this and hope for the best with the next release

**Comment by Baraka24** [comment]
Hello @ulfgebhardt,

As we both know, it works... but occasionally, it doesn't seem to on your side, even when we paired together. I've just taken a thorough look at the codebase, and everything appears to be functioning as expected. I believe we can consider this issue resolved.

We truly appreciate your detailed reporting and your engagement with Cypht. Your feedback is invaluable, and we look forward to hearing from you again in the future.

Thank you!

**Comment by mercihabam** [comment]
Before we close, there might be something hindering the normal behavior from showing up on Ulf's side. @Baraka24, do you mind reporting any additional details you came across during your pairing session, if any?

**Comment by Baraka24** [comment]
@mercihabam, it worked most of the time, but I couldn’t understand why it didn’t work consistently. @ulfgebhardt had to reload the page and try reproducing the issue again. In other cases, it didn’t work, possibly because the page hadn’t fully reloaded on his end.

**Comment by mercihabam** [comment]
Ok, let's hope that with the next release, this gets resolved for him.

**Comment by mercihabam** [comment]
Despite the issue being unreproducible on our side, here is one more layer of [fix](https://github.com/cypht-org/cypht/pull/1643), increasing the probability of not encountering it in the next release.

**Comment by ulfgebhardt** [comment]
Thank you
