### ISSUE TITLE
Change CSS/JS path to load from

### ISSUE THREAD

**Issue by Yamakasi** [cypht-org/cypht#212]
Due some integration issues I need to be able to change the path where all CSS and JS is loaded from.

Can't we make some /static folder and put it in there that would be much easier.

At least looking back to the root would be great!

JS is kinda doable but CSS is a pain. 

I hope I can fix this asap :)

**Comment by jasonmunro** [comment]
This would be a reasonably big change in order to support both production and debug mode. i'm not sure changing this in Cypht makes sense. When the config gen script is run it generates the combined assets and puts them in the site/ dir, which is basically like a static/ dir.

**Comment by Yamakasi** [comment]
OK, this should be site.js then ?

I have bene looking through and i saw what you were doing but was not sure.

**Comment by jasonmunro** [comment]
site.js is the combined javascript from all the enabled module sets (built with the config gen script), however sometimes modules need to include there own stand alone js/css, and these are put under the site/modules directory by the config gen script.

**Comment by marclaporte** [comment]
If someone needs this, please re-open, and explain how you plan to integrate in other apps so we make this generic and future-proof.
