### ISSUE TITLE
Importing Contacts

### ISSUE THREAD

**Issue by mitnworb** [cypht-org/cypht#27]
What is your long term plan for contacts?  Is there a way to import them currently?  So far I am very impressed. This is exactly what I have been looking for.

**Comment by jasonmunro** [comment]
There is no import currently, but it's been requested a few times already, and it's definitely something we want to do. Long term I would like to see:

- import/export, bulk or single contact, probably vcard based
- LDAP/active directory support
- better integration of contacts provided by a service. There is already very preliminary support for gmail contacts when you add a gmail account. I would love to expand this to any other E-mail provider that supports something similar (outlook probably, maybe others).

I appreciate the feedback and support! Once I wrap up a few more SMTP related things, I'm going to get back to improving contacts. Hopefully soon :).

Thanks again for the feedback!

**Comment by jasonmunro** [comment]
Been doing a very small amount of contact system updates, (paging, gmail contact integration). The main thing I want to get in place here first is import/export, so that is next on my list.

**Comment by Yamakasi** [comment]
I was wondering what the idea/status is here.

I see that there is not inCypth storage which would be a start if you ask me. I don't see a usage for ldap only in corporate usage and as ldap searches will be open you sometimes don't want to share even in companies your contacts with others so I'm curious if this is idea was for inCompany users or not.

I have tested the local storage but I'm not sure where it's stored as when I end my session by logout the users I added are gone as well. 

I think it's most easy to extend the local storage with an SQL way and maybe even with a caldav/carddav server if people would like to have that as it's a native way protocol of storing contacts.

**Comment by dumblob** [comment]
I'm not sure what the plain is, but I wouldn't want to make Cypht responsible for locally storing and maintaining the contact list. I see Cypht as a thin layer between an email/contact/... service and a user (so far the DB is optional and offers e.g. the luxury of user settings). Therefore I would expect Cypht to at most temporarily cache contacts (and for this caching purpose we don't need to persist the contacts).

**Comment by jasonmunro** [comment]
Contacts have grown a bit since this discussion:
- We now have full support for LDAP contacts (multiple sources, read/write)
- Gmail contacts are still pretty limited (read only, max 500 per account)
- Making progress on CardDav server contacts, which will be very much like Gmail, thin layer

Whenever I get a chance to get around to this, I'm confident I want it to:
- Work with all our supported contact sources (Gmail, CardDav, local, LDAP, whatever)
- Support both bulk import and export
- use vCard format

**Comment by marclaporte** [comment]
Basic import exists:
![2024-05-01_135946](https://github.com/cypht-org/cypht/assets/1004261/7fef7876-1e76-425f-9c5f-06db867f3e5d)
