### ISSUE TITLE
Coloring the messages in list to get a fast overview of the account they belong to

### ISSUE THREAD

**Issue by codiflow** [cypht-org/cypht#450]
## 🗣 Suggestion
I'd like to have a fast overview if there are (important) mails from some of my accounts in my inbox. As I added 9 accounts its sometimes a bit messy in my inbox. To keep me informed it would be great to have a color attached to every smtp account which gets applied as a background (or marker or anything else) so see to which account the incoming mail belongs to.

As I'm firm with PHP, CSS and HTML I would implement this feature but first I wanted to ask, if there were feature requests like mine in the past or if theres an easier way to implement this. My plan was to add a seperate field to the IMAP servers with the color which is then used for this. So I can easily change this for every account if I need to.

I found this answer on a closed issue but I don't know where to apply this styling and if thats really what I had in mind: https://github.com/jasonmunro/cypht/issues/20#issuecomment-146524094

![Unbenannt](https://user-images.githubusercontent.com/43847817/104243533-fccfc300-5460-11eb-8e0d-5f0e17459131.png)

I would be happy to build this feature as I think this would improve my productivity a lot :-)

**Comment by marclaporte** [comment]
This is a fantastic idea! I will use it!

A related idea: https://github.com/jasonmunro/cypht/issues/9 (I would add colors to messages from certain people)

Thanks!

**Comment by codiflow** [comment]
For those who want a "fast fix" for that:
Every "message row" has the whole emailaddress / smtp account name set as css class name. So styling it in your browser is no big thing.

So just add this to have a red background on every email from that account for example:
`.my\@mailaddress\.com { background-color: red }`

**Comment by codiflow** [comment]
Using the Firefox addon Stylus this took me 5 minutes:

![grafik](https://user-images.githubusercontent.com/43847817/104373269-cfe2e500-5520-11eb-868e-c366ae55a7da.png)

**Comment by marclaporte** [comment]
Thank you @codiflow! This is a great quick workaround until we figure out a built-in solution.

**Comment by jasonmunro** [comment]
This is a neat idea. @codiflow your solution is exactly how I was thinking we should code this up.  We can create a new module set, and for each account you can pick background/foreground colors, and then we use the row classes you identified to apply the CSS rules. Should be a pretty easy module set to build.

**Comment by jasonmunro** [comment]
Initial version of a "highlight" module set is pushed to master. I have not added it to the sample ini yet but you can enable it with:

```modules[]=highlights```

It supports rules to alter background or text colors based on 3 sources (E-mail, RSS, Github) and within each you can setup per source limits (so just E-mail account foo for example, or E-mail accounts foo + bar), AND for E-mail you can also add a flag (unseen, flagged, etc). Finally each rule can also have the CSS !important flag set to force an override of a previously applied rule.

Just committed this and so far testing is good but it likely has some kinks to work out.

**Comment by marclaporte** [comment]
For the record, here is the code: https://github.com/jasonmunro/cypht/tree/master/modules/highlights

**Comment by marclaporte** [comment]
I saw this in another webmail client, and I liked it: A color for flagged messages.

**Comment by jasonmunro** [comment]
> I saw this in another webmail client, and I liked it: A color for flagged messages.

well good thing the highlight module set already supports that :)

**Comment by marclaporte** [comment]
This already exists:
![2024-05-01_135458](https://github.com/cypht-org/cypht/assets/1004261/ab9718cf-74bc-43de-8c77-1bb2273f5762)
