### ISSUE TITLE
Proposal: Deprecate POP3 support if no one steps up to maintain it

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#452]
We have multiple issues with POP3:
https://github.com/jasonmunro/cypht/labels/pop3

Clearly, it's not working very well.

Our energy should be on the present and the future, not the past. We should focus on making IMAP rock stable. I see no reason to use POP3. Please someone explain to me the use case.

And then, get JMAP rock stable:
https://github.com/jasonmunro/cypht/issues/180

And then, with any remaining energy, support EWS:
https://github.com/jasonmunro/cypht/issues/247

Now, I know there are some POP3 users and fans. This is your time to step up and say "I will help". We need coders. If you can't code, we need someone to lead a fundraising campaign so we can hire coders.

I propose to give community members 2 months to come up with a plan. In the absence of one, we mark POP3 issues / code / etc. as deprecated. And in the issues, we indicate that we are looking for help. If no one steps up by 2021-12-31, we remove all POP3 related code from Cypht.

Thoughts?

**Comment by jasonmunro** [comment]
I agree. If we end up removing it I might archive in its own repo with the hope someone someday wants to revisit :)

**Comment by marclaporte** [comment]
I removed POP3 issues from blockers to release 1.2:
https://github.com/jasonmunro/cypht/projects/2

**Comment by kmpoppe** [comment]
There might, for some VERY strange reason, Mx providers that will not allow IMAP but only POP3 ... Even though they'd deserve a good slap!

Are you seeking to remove the support for POP3 completely to get it out of the current repo? If so, would it make sense to build a new repo that supplies a _module_ that would enable POP3 again - but can be supported without touching the main repo?

Just my 2 cents.

K

**Comment by marclaporte** [comment]
Mostly, I want to align expectations with reality. If we don't expect to have brainpower to maintain a feature, we should remove it, or tag it as experimental.

**Comment by henrique-borba** [comment]
I agree. I don't think we must call it "experimental" because in my perspectice it seems like it is a kind of early stage feature that WILL be updated. I recommend to just call it deprecated for a future release and just give it a deprecation deadline.

**Comment by marclaporte** [comment]
+1 for "deprecated"

**Comment by Master0ne** [comment]
+1 for getting rid of POP3 support entirely. Away with the cruft for developers to be able to concentrate on more important stuff.

**Comment by marclaporte** [comment]
RFC 9899 IMAP v POP 
https://www.youtube.com/watch?v=NAkAMDeo_NM&t=468s

**Comment by marclaporte** [comment]
So upcoming Cypht 1.5 will no longer have POP support.

**Comment by marclaporte** [comment]
Google Is Ending Gmailify and POP Support
https://slashdot.org/story/447452
