### ISSUE TITLE
If someone closes browser, and has unsaved changes to settings, attempt to warn user (was Profiles not saved)

### ISSUE THREAD

**Issue by ghost** [cypht-org/cypht#523]
Brand new install on RHEL connecting to an IMAP server.

- Created 3 new profiles.  
- The profiles work. 
- Log out- 
- Log in 
- Profiles gone.

This is a clean out-of-the-box install. Not sure what it's using for configuration data persistence. If it's "nothing", there should probably be a warning of some sort.

**Comment by marclaporte** [comment]
Yeah, it should warn you on log out (Do you want to save setting? Yes/No)

Can you try Settings -> Save?

Thanks!

**Comment by tpcarmen** [comment]
> Yeah, it should warn you on log out (Do you want to save setting? Yes/No)

Sorry, I needed to get webmail running so I nuked the install and don't have an instance to try it on.

FWIW, I think I remember the "add profile" screen already has a save button on it, so a second save shouldn't be needed.

**Comment by marclaporte** [comment]
Done: https://github.com/cypht-org/cypht/pull/669
