### ISSUE TITLE
Use allinkl as email provider

### ISSUE THREAD

**Issue by horphi0815** [cypht-org/cypht#565]
## 💬 Question
Hi,

i´d like to use all-inkl.
Imap Setup is standard. 
But Cypht does not connect.

Under Incoming email servers and Outgoing email servers enter <your-login>.kasserver.com. Select SSL/TLS as the encryption method. Adjust the ports as well. Enter 993 as the port for Incoming e-mail servers and 465 for Outgoing e-mail servers.

https://all-inkl.com/wichtig/anleitungen/programme/e-mail/outlook/2019_546.html?suche=SMTP&textsuche=ja

Does Cypht support allinkl?

BR

Phil

**Comment by marclaporte** [comment]
Hi @horphi0815 

Sorry you are having issues. I have not tried all-inkl, but email is standard so I am highly confident it will work with the right settings.

Please join us on https://gitter.im/cypht-org/community so we can troubleshoot.

We could also add here: https://github.com/jasonmunro/cypht/blob/master/modules/nux/services.php so it will be easier for end users.

Thanks!

**Comment by marclaporte** [comment]
There is a debug mode: https://cypht.org/install.html

**Comment by marclaporte** [comment]
Please try latest code as @josaphatim added it to the new user experience module: https://github.com/jasonmunro/cypht/pull/683

**Comment by marclaporte** [comment]
@horphi0815 We need you!

We now have 3 branches: https://github.com/cypht-org/cypht/wiki/Lifecycle

**Comment by marclaporte** [comment]
@horphi0815 we need you!

**Comment by horphi0815** [comment]
@marclaporte i can send you some credentials

**Comment by horphi0815** [comment]
@marclaporte 
i cant send you a private message...button is not available

**Comment by marclaporte** [comment]
My domain name is marclaporte.com
My email is my first name at that domain name.

Thanks!

**Comment by josaphatim** [comment]
MR proposed to fix for Cypht master in nux module, but It is working fine in IMAP - SMTP - JMAP servers
For Cypht v1 it is working just fine

**Comment by marclaporte** [comment]
Thank you @josaphatim for https://github.com/cypht-org/cypht/pull/1260
