### ISSUE TITLE
Gmail and Cypht: Sorting by "Sent date" doesn't show recent emails ("Arrival date" is OK)

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#616]
<img width="1060" alt="2022-09-04_215743" src="https://user-images.githubusercontent.com/1004261/188345788-7b25b533-7cd1-4e8e-86f9-4d2605ee1341.png">

**Comment by marclaporte** [comment]
Related: https://github.com/jasonmunro/cypht/issues/378

**Comment by marclaporte** [comment]
Related: https://github.com/cypht-org/cypht/pull/765

**Comment by marclaporte** [comment]
Likely solved (to be tested)
- https://github.com/cypht-org/cypht/pull/1120
- 1.4: https://github.com/cypht-org/cypht/commit/103e98f09f5e1d3ff5696841ac2876fcfb816c41

**Comment by marclaporte** [comment]
I tested on 2024-07-23 and the issue persisted.

**Comment by kroky** [comment]
Indeed, this was another problem, fixed here: https://github.com/cypht-org/cypht/commit/82ae81754f10661b43d0ef3985b85abc51b3e2fe
