### ISSUE TITLE
Rework the login page

### ISSUE THREAD

**Issue by ElvisAns** [cypht-org/cypht#621]
## 🗣 Suggestion

Cypht's login page looks a bit too old.
We need to rework a little bit it design...

![image](https://user-images.githubusercontent.com/35831811/190774518-350f28a3-a5e7-4006-ae6b-313103f9f488.png)

**Comment by ElvisAns** [comment]
Solution is coming https://github.com/jasonmunro/cypht/pull/623

**Comment by marclaporte** [comment]
Done in v2
