### ISSUE TITLE
Show space used/available

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#626]
KolabNow offers this in the Roundcube interface. Gmail shows you. And here is how SOGo shows it:
![2022-09-24_123014](https://user-images.githubusercontent.com/1004261/192108916-065eeeb1-0454-4f30-8d53-04f9d7f52f3a.png)

This should be quite discreet or even hidden until you are using a large part of your quota.

**Comment by dumblob** [comment]
Discreet yes, hidden no :wink:. Useful feature btw.!

**Comment by marclaporte** [comment]
SnappyMail shows disk space per folder:
![image](https://github.com/cypht-org/cypht/assets/1004261/de5d4185-b3af-4c14-b3ac-fe8c56561224)

**Comment by marclaporte** [comment]
Other ideas:
- It would be nice to also have the number of emails (if this doesn't hinder performance)
- Folders vs sub-folders would be nice as well. So you can see total for a folder (including its sub-folders), and click to get more info on a specific folder.

**Comment by Baraka24** [comment]
Closing, as worked on in [PR](https://github.com/cypht-org/cypht/pull/1102) and lastly issue related solved in [PR](https://github.com/cypht-org/cypht/pull/1218).
