### ISSUE TITLE
500 on sending mail

### ISSUE THREAD

**Issue by capocasa** [cypht-org/cypht#650]
## 🐛 Bugreport

A '500 server error' page shows up on sending mail on my installation.

It's a debian-bullseyse system running Apache and PHP 7.4.30. It was first reported on gitter by Calaad. This is from his report, my error was identical.

```
[Fri Jun 24 11:10:21.900376 2022] [php7:notice] [pid 62092] [client XXX.XXX.XXX.XXX:55770] PHP Notice:  Trying to access array offset on value of type null in /usr/local/share/cypht/modules/smtp/modules.php on line 716
[Fri Jun 24 11:10:21.900406 2022] [php7:notice] [pid 62092] [client XXX.XXX.XXX.XXX:55770] PHP Notice:  Undefined index: draft in /usr/local/share/cypht/modules/smtp/modules.php on line 716
[Fri Jun 24 11:10:21.900850 2022] [php7:error] [pid 62092] [client XXX.XXX.XXX.XXX:55770] PHP Fatal error:  Uncaught Error: Call to a member function select_mailbox() on bool in /usr/local/share/cypht/modules/smtp/modules.php:1435\nStack trace:\n#0 /usr/local/share/cypht/modules/smtp/modules.php(716): delete_draft()\n#1 /usr/local/share/cypht/lib/modules_exec.php(175): Hm_Handler_process_compose_form_submit->process()\n#2 /usr/local/share/cypht/lib/modules_exec.php(153): Hm_Module_Exec->run_handler_module()\n#3 /usr/local/share/cypht/lib/dispatch.php(220): Hm_Module_Exec->run_handler_modules()\n#4 /usr/local/share/cypht/lib/dispatch.php(190): Hm_Dispatch->process_request()\n#5 /usr/local/share/cypht/site/index.php(50): Hm_Dispatch->__construct()\n#6 {main}\n  thrown in /usr/local/share/cypht/modules/smtp/modules.php on line 1435

```

### Version & Environment
Rev: 68239a70befe06bb7cddb180a6a858c4f989259b

OS:  Debian Bullseye PHP 7.4.30 on Apache

### Steps to reproduce
1. Install cypht according to instructions
2. Set up an IMAP server and configure cypht to have IMAP login
3. Send a mail.
4. Observe 500

**Comment by capocasa** [comment]
[hm3.ini.txt](https://github.com/jasonmunro/cypht/files/9902311/hm3.ini.txt)

This is the used configuration

**Comment by marclaporte** [comment]
@capocasa Do you remember if this was for sending a newly composed email or forwarding an email?

I have seen a weird issue once or twice for forwarding but not the other.

**Comment by marclaporte** [comment]
@capocasa 
This was merged: https://github.com/cypht-org/cypht/pull/651

Please retest.

**Comment by marclaporte** [comment]
@capocasa We now have 3 branches: https://github.com/cypht-org/cypht/wiki/Lifecycle

**Comment by marclaporte** [comment]
Closing as outdated.

We now have revamped and official Docker:
https://hub.docker.com/r/cypht/cypht

Please use latest stable version: https://github.com/cypht-org/cypht/releases
