### ISSUE TITLE
Add new contacts source

### ISSUE THREAD

**Issue by Liia-Dulher** [cypht-org/cypht#660]
Is there any way to add contacts from my database? I would like to use it as new source or replace local emails with it. Also I can not find where local contacts are stored and how they are loaded.

**Comment by kambereBr** [comment]
Hello @Liia-Dulher, here's a pending Pull Request (https://github.com/cypht-org/cypht/pull/845) that introduces CSV import functionality to the existing local contacts module. Before finalizing it, I'd love to get your feedback and suggestions. The pull request is still a draft, so your insights at this stage would be valuable.

To give you a better idea of how it works, I've attached a demo GIF showcasing the implemented feature in action. Have a look when you get a chance

**Comment by marclaporte** [comment]
"Persistent data stored between logins is encrypted with a key derived from your clear text password, which is obviously not stored anywhere"
Source: https://www.cypht.org/security.html

**Comment by marclaporte** [comment]
@Liia-Dulher coming soon: https://github.com/cypht-org/cypht/pull/904

**Comment by kambereBr** [comment]
@Liia-Dulher the Pull Request https://github.com/cypht-org/cypht/pull/904, is already merged.
