### ISSUE TITLE
How can I connect my (All-Inkl) IMAP account?

### ISSUE THREAD

**Issue by juekr** [cypht-org/cypht#672]
## 💬 How can I connect my (All-Inkl) IMAP account?

I have several email accounts at the German hosting company All-Inkl and I have several email clients that access them over Imap perfectly fine. But (with the same settings) Cypht keeps claiming that my credentials are incorrect: "Unable to save this server, are the username and password correct?". I tried any combination of TLS/SSL but with no luck. How can I debug and possibly solve this?

**Comment by marclaporte** [comment]
If you supply me a test account (send me info in private), I can assign a junior dev to investigate.

**Comment by juekr** [comment]
Hey, thanks for the offer. I have Cypht running in my LAN only, but I can give you an account on my IMAP server?

**Comment by marclaporte** [comment]
Sure, that's fine.

You can find me in here:
https://app.gitter.im/#/room/#cypht-org_community:gitter.im

**Comment by marclaporte** [comment]
@juekr ok I received info. We'll investigate.

If it makes you feel better, you are not alone: https://github.com/jasonmunro/cypht/issues/565

**Comment by juekr** [comment]
Actually, it does ;-) I've already seen the issue, but I couldn't really get the debug mode to work (I guess, I'm just kinda dumb when it comes to stuff like that).

**Comment by josaphatim** [comment]
> ## 💬 How can I connect my (All-Inkl) IMAP account?
> I have several email accounts at the German hosting company All-Inkl and I have several email clients that access them over Imap perfectly fine. But (with the same settings) Cypht keeps claiming that my credentials are incorrect: "Unable to save this server, are the username and password correct?". I tried any combination of TLS/SSL but with no luck. How can I debug and possibly solve this?

<img width="1143" alt="Screenshot 2023-02-22 at 11 33 22" src="https://user-images.githubusercontent.com/80334370/220580334-2e2e9f2f-0dde-4113-9ae5-5b1d57c8e59c.png">

After many tries without touching the code i got it work i'm still investigating to know the cause

**Comment by marclaporte** [comment]
Ok, once you figure out, it would nice to add to https://github.com/jasonmunro/cypht/blob/master/modules/nux/services.php

**Comment by marclaporte** [comment]
@juekr Can you please test https://github.com/cypht-org/cypht/pull/683 ?

Thanks!

**Comment by marclaporte** [comment]
@juekr please

**Comment by marclaporte** [comment]
@juekr last call :-)

**Comment by juekr** [comment]
Oh sorry, I totally missed your messages. Happy to try. How can I download and test this exact branch/tag/version? Sorry, I'm not a coder and don't know too much about how this stuff works 😉

**Comment by marclaporte** [comment]
This is part of regular releases of Cypht. So just install the latest stable version (2.4.0 as of now)
https://github.com/cypht-org/cypht/releases

**Comment by marclaporte** [comment]
Thank you @josaphatim for https://github.com/cypht-org/cypht/pull/1260

**Comment by juekr** [comment]
I still cannot get the All-Inkl option in the server dropdown to work – but manually adding All-Inkl IMAP and SMTP servers seems to work now. 👍

**Comment by marclaporte** [comment]
https://github.com/cypht-org/cypht/pull/1260 is still in review, but it will be confirmed soon. Thus, this will be part of the next Cypht release (2.4.1 or 2.5.0).

Thank you @juekr!
