### ISSUE TITLE
We can now search in a folder. Let's add "include subfolders", "all folders" and special folders (sent, draft, archive, etc.)

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#676]
The current search in Cypht is quite impressive in that you can search throughout various mail accounts, which is not possible in Roundcube as per: https://github.com/roundcube/roundcubemail/issues/4972

https://github.com/jasonmunro/cypht/tree/master/modules/advanced_search is very powerful, but there is a an issue that you need to indicate each folder you want to search in.

In contrast, here is what Roundcube offers:
![2023-02-22_103531](https://user-images.githubusercontent.com/1004261/220673325-83eca503-b51b-41f4-a081-6acce8472733.png)

So let's add what Roundcube does. And given Cypht's multi-account feature, we can also add:
* Search in all sent folders
* Search in all draft folders
* Search in all archive folders (here subfolders would be useful)
* etc.

It will be really efficient when combined with https://github.com/jasonmunro/cypht/issues/306

**Comment by marclaporte** [comment]
Also, there should be a filter for subscribed vs not subscribed, as non-subscribed folders are often more archival and thus, not so interesting to search through (of course, sometimes they are so we still want to be able to)
https://github.com/jasonmunro/cypht/pull/622

**Comment by marclaporte** [comment]
"Is it too much to ask, for example, for a webmail client with global search? The only one that I found so far is Roundcube, which can do a global search (all parts, all folders) with "just" 4 additional clicks. Why is that? I had a server running Horde Groupware in 2013 that could do that."
https://www.reddit.com/r/selfhosted/comments/16d3ae0/the_sad_state_of_selfhosted_webmail/

I agree. We will work on this.

**Comment by marclaporte** [comment]
Related discussion in SnappyMail: https://github.com/the-djmaze/snappymail/issues/196

**Comment by TheDigitalOrchard** [comment]
I like how Apple Mail handles searches, by presenting a "scope selection" as the search term is being entered.

<img width="420" alt="apple-mail-search" src="https://github.com/cypht-org/cypht/assets/3195423/f26fff6e-f080-4cdd-8a20-0484593c3e02">

Selecting a scope is optional, but very intuitive. The tag-based interface is easy to tweak at any time.

<img width="387" alt="apple-mail-search-scope" src="https://github.com/cypht-org/cypht/assets/3195423/19273671-56b7-4d6a-b254-24d92710962b">

And to select the account-level scope, you just swap which "Inbox" is selected in the left column. You can search across all accounts, or a specific one. It's very quick and simple.

**Comment by jacob-js** [comment]
A search in all folders has been implemented: https://github.com/cypht-org/cypht/pull/1337.
Note that it will be quite slow for large mailboxes due to IMAP limitations, as it cannot handle a search operation across multiple folders in a single go. For now, we have to go through each folder manually and gather results from each one.

**Comment by marclaporte** [comment]
Related discussion: https://github.com/cypht-org/cypht/pull/1582
