### ISSUE TITLE
Warn about potential missing attachment when sending an email

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#684]
Something like this: https://www.claws-mail.org/plugin.php?plugin=attachwarner

**Comment by marclaporte** [comment]
AI: Seems like overkill to add a dependency for this.

A simple example: https://github.com/roundcube/roundcubemail/blob/master/plugins/attachment_reminder/attachment_reminder.php

We can easily get translators to identify the main terms for currently supported languages.

I like the idea of machine learning and AI for more advanced use cases. Related: https://dev.tiki.org/Machine-Learning-for-Email

**Comment by Shadow243** [comment]
Pull Request https://github.com/cypht-org/cypht/pull/839 has been submitted, introducing the feature to warn users about potential missing attachments when composing emails.
