### ISSUE TITLE
updating cypth and windows 1257 error on php 8.2

### ISSUE THREAD

**Issue by mcbmcb0** [cypht-org/cypht#732]
## 💬 Question
I've updated to php 8.2.7 (from 7.3.3) and now see the following:
`PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) contains invalid encoding "windows-1257" in /var/www/cypht/modules/core/message_functions.php`
1. strangely, i don't even know if i have the current version of cypth as can't see a current version displayed nor find info on updating.... is it a reinstall or does it self update?
2. if cypht is up to date... any clues on that `mb_convert_encoding()` error message? 
thanks!

**Comment by mcbmcb0** [comment]
further, i noticed that the function creating the error is unchanged in the new cypht 1.4, and that this issue has appeared in nextcloud and roundcube as well - eg [https://github.com/roundcube/roundcubemail/issues/1004](https://github.com/roundcube/roundcubemail/issues/1004). apparently: 
> as of PHP 8.0.0, a ValueError is thrown if the value of to_encoding or from_encoding is an invalid encoding

adapting the roundcube patch i hacked this into message_functions.php:

```
$fld = substr($fld, (strpos($fld, '?') + 1)); // EXISTING line 403
      
$alt_charset = ['UTF-7'=>"UTF7-IMAP", 'WINDOWS-1257'=> "ISO-8859-13"]; 
if(array_key_exists(strtoupper($charset), $alt_charset)){// MB
   $charset = $alt_charset[strtoupper($charset)];
 }

if (strtoupper($encoding) == 'B') { // existing line 404
...
```

this appears to work. the array can obviously expand to other similar problems (eg windows 1250 and 1265 are reported as problems by some).
i tried using iconv for these character sets but had lots of '`Wrong encoding`' errors so didn't bother.

this is temporary and not elegant but may help someone until a proper fix is found.

**Comment by marclaporte** [comment]
Thank you @mcbmcb0 

@josaphatim and I will investigate along with your other PHP8 report.

**Comment by marclaporte** [comment]
FYI, Cypht is bundled in Tiki so it will have a lot of extra eyeballs in this context:
- https://doc.tiki.org/PHP8
- https://doc.tiki.org/Cypht

FYI: Historically, Cypht tries to support a large number of PHP versions. I want to slowly move us in a direction where we keep up with new PHP versions and more frequent version releases. And we'll introduce Long Term Support (LTS) versions for those that want/need to use on older versions of PHP. Something closer to https://tiki.org/Tiki-Versions

**Comment by marclaporte** [comment]
@mcbmcb0 Please confirm the issue is solved in master.

**Comment by mcbmcb0** [comment]
yes! the current master appears to work for me on php8.2.
thanks
