### ISSUE TITLE
Plans to support Chinese?

### ISSUE THREAD

**Issue by foxh1s** [cypht-org/cypht#733]
## 🗣 Suggestion
Great webmail! 
I have been using it for two weeks now, and I would like to introduce more colleagues to use it.
Do you have any plans to support Chinese language?

**Comment by marclaporte** [comment]
I would love to add more languages. Can you find someone to contribute a translation?

**Comment by marclaporte** [comment]
@foxh1s Can you find some translators?

**Comment by marclaporte** [comment]
Thank you for the translation!

Discussion about Docker continues here: https://github.com/cypht-org/cypht/issues/748
