### ISSUE TITLE
Broken icon image when using a theme that alters icon colors

### ISSUE THREAD

**Issue by jasonmunro** [cypht-org/cypht#741]
## 🐛 Bugreport

I noticed this on mobile with a dark theme. The "three dots" icon above a message list is not displaying correctly.

### Version & Environment

Rev: current master

OS:  NA

### Steps to reproduce
1. change to one of the dark themes
2. open a message list on mobile
3. observe the broken icon in the upper right of the page
4. ...
5. Profit

Themes can modify icon colors, which happens here: https://github.com/cypht-org/cypht/blob/master/modules/themes/modules.php#L193 This code adds a "fill" attribute to the svg tag. However there MUST be a space at the end of the svg tag before the closing characters, otherwise the fill attribute is not correctly formatted. For example:

```<svg path="..." />```

this is ok, there is a space before the tag closes

```<svg path="..."/>```

This is not ok, there is no space before the tag closes. Without the space adding the fill attribute causes the path and fill attributes to not have a space separating them which is invalid.

**Comment by marclaporte** [comment]
Thank you @jasonmunro 

This is a good first commit for one of our new devs.
