### ISSUE TITLE
Docker continuous compilation

### ISSUE THREAD

**Issue by wangxiaoerYah** [cypht-org/cypht#748]
Can I add Docker workflow to the current branch? Instead of in another repository,.

I want to create two docker branches for it, stable and nightly

**Comment by marclaporte** [comment]
Good question!

FYI, the project evolved from personal repo to an organization:
https://unencumberedbyfacts.com/2023/06/14/cypht-rebooted/

So the commit review process release process is now handled by a team.

We have yet to review the Docker part. We'll soon e-meet to discuss this. Can you join us?

**Comment by marclaporte** [comment]
Let's continue the discussion here: https://github.com/cypht-org/cypht-docker/issues/5
