### ISSUE TITLE
Remove all references to the #hastymail chatroom on Freenode (IRC), and continue focus on Gitter.

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#760]
We started using Gitter as a community chatroom. And Gitter merged into Matrix: https://matrix.to/#/#cypht-org_community:gitter.im
https://github.com/cypht-org/cypht/issues/352

The room now has 87 people:
![2023-09-10_122447](https://github.com/cypht-org/cypht/assets/1004261/41b7dae8-56ed-4ee4-86a3-2a834ed1b1d7)

I just checked on IRC, and there was just one person.

So let's remove all references to IRC, and converge everyone on Gitter.

**Comment by marclaporte** [comment]
Started: https://github.com/cypht-org/cypht/commit/5fa3fd7d22b4ea6a1d5d62c5ddd0ff2477a1c71c

**Comment by jangliss** [comment]
Yup, that one person on Freenode/#hastymail and libera/#cypht is me. I'd worked with Jason on SquirrelMail and HastyMail when he first started it. I was keeping the seat warm, so to speak.  I've set the topic on Freenode, but it appears Jason never added me as an admin on Libera so I cannot update the topic there to notify folks.  Might need to get him to add one of us to change it.

**Comment by marclaporte** [comment]
Thank you @jangliss !

FYI @jasonmunro is really busy these days so we converted to a GitHub organization, and many devs are active:
- https://unencumberedbyfacts.com/2023/06/14/cypht-rebooted/
- https://github.com/orgs/cypht-org/people
- https://openhub.net/p/cypht/contributors?query=&time_span=&sort=twelve_month_commits

@jangliss This is a great time to come back and help us take Cypht to the next level!

**Comment by marclaporte** [comment]
Done: https://github.com/cypht-org/cypht-website/pull/40
