### ISSUE TITLE
Move to Bootstrap 5

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#762]
In 2017, Roundcube moved to Bootstrap: https://github.com/roundcube/elastic/issues/21

SnappyMail also uses Bootstrap (inherited from RainLoop):
https://github.com/the-djmaze/snappymail/tree/master/vendors/bootstrap

Bootstrap is the most popular of comparable frameworks:
- https://w3techs.com/technologies/overview/css_framework
- https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)

The Tiki.org community (which is a main contributor to Cypht nowadays) has deep expertise with Bootstrap, and will lead this transition: 
- https://doc.tiki.org/Bootstrap
- https://doc.tiki.org/Cypht

We will start with a prototype to gather feedback from the community.

This will, among other things, replace [Tingle](https://github.com/robinparisi/tingle
). Please see: https://github.com/cypht-org/cypht/blob/master/modules/sievefilters/assets/tingle.min.css
This came in via:
- https://github.com/cypht-org/cypht/commit/9c6767c1130f333332ffc4060f88615baabc8865
- https://github.com/cypht-org/cypht/commit/e7a9cda9068cc65d55268989d302b7d5266ba165

**Comment by marclaporte** [comment]
Once we are using Bootstrap 5, we can easily add themes like the ones from https://github.com/thomaspark/bootswatch/

**Comment by marclaporte** [comment]
Draft: https://github.com/cypht-org/cypht/pull/828

**Comment by marclaporte** [comment]
The MR is ready.

**Comment by marclaporte** [comment]
At a meeting yesterday, @alvinBM indicated that future steps (in distinct PRs) include adding some themes from [Bootswatch](https://github.com/thomaspark/bootswatch) and testing the integration in Tiki.

**Comment by mmarcwabo** [comment]
@alvinBM Great work so far.

**Comment by marclaporte** [comment]
Congrats and thank you @alvinBM for delivering this strategic project! https://github.com/cypht-org/cypht/pull/828

**Comment by marclaporte** [comment]
Bootswatch is coming: https://github.com/cypht-org/cypht/pull/921
