### ISSUE TITLE
Forward attachments

### ISSUE THREAD

**Issue by rikberkelder** [cypht-org/cypht#764]
## 🗣 Suggestion
I forward all of my incoming invoices to my accountant. This works just fine in most mail clients, but with Cypht it seems like attachments from the original e-mail are not included in the forwarded e-mail. It would probably make sense to do so, or provide an option to.

**Comment by marclaporte** [comment]
Indeed.

@josaphatim I remember you worked on this. Please advise.

**Comment by josaphatim** [comment]
@marclaporte I proposed merge request for this issue.

**Comment by marclaporte** [comment]
For the record: We also saw issue here: https://gitlab.com/tikiwiki/tiki/-/merge_requests/3594
