### ISSUE TITLE
Menu for list controls on mobile has an incorrect icon

### ISSUE THREAD

**Issue by jasonmunro** [cypht-org/cypht#766]
## 🐛 Bugreport

The list controls for mobile defined in modules/core/message_list_functions.php at line 476 has the following:

```
    <div class="list_controls on_mobile">'.$search_field.'
        <img alt="" src="'.Hm_Image_Sources::$three_dot.'" width="20" height="20" onclick="listControlsMenu()"/>
        <div id="list_controls_menu" classs="list_controls_menu">'.$refresh_link.$source_link.$config_link.'</div>
    </div>';
```

However the icon that shows up is an "x"

### Version & Environment
master branch on debian unstable

### Steps to reproduce
1. access cypht using a mobile device
2. observe the "x" icon where "three dots" should be.

**Comment by jasonmunro** [comment]
Looks like the problem is the Hm_Image_sources "three_dot" svg definition is incorrect, located here:

https://github.com/cypht-org/cypht/blob/master/lib/output.php#L133

that value should be changed to something like:
```
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%3E%0A%20%20%3Cpath%20d%3D%22M0%200v2h2v-2h-2zm3%200v2h2v-2h-2zm3%200v2h2v-2h-2z%22%20transform%3D%22translate%280%203%29%22%20%2F%3E%0A%3C%2Fsvg%3E
```

Might need to tweak some CSS after fixing the icon definition to line it up properly.

**Comment by marclaporte** [comment]
@jasonmunro Are you OK with this fix?

**Comment by Yannick243** [comment]
Pull request already merged: [https://github.com/cypht-org/cypht/pull/768](https://github.com/cypht-org/cypht/pull/768)
