### ISSUE TITLE
2FA authentication should not be enabled until we confirm user has configured google authenticator

### ISSUE THREAD

**Issue by ElvisAns** [cypht-org/cypht#772]
### Let's consider the following scenario
1. Enable 2fa authentication
2. Logout without scanning the setup QR code (this may happen to end users)
3. Next time you login Cypht will ask you the 6digit code from Authenticator and you loose access to your account

### Proposed solution
Before asking users to enter TOTP on login, we have to confirm they have google authenticator paired. Usually this is done by asking them to put the current TOPT during the configuration  process and if match, we now enforce 2FA on next login.

**Comment by marclaporte** [comment]
@ElvisAns Does the PR look good to you?

**Comment by ElvisAns** [comment]
@marclaporte testing now, will share some feedback

**Comment by ElvisAns** [comment]
@Yannick243 it sounds good on my end

https://github.com/cypht-org/cypht/assets/35831811/d473311f-9334-4ad6-9189-d62834b7daba

@marclaporte what do you think about the flow above? User experience wise

**Comment by marclaporte** [comment]
I refer to @johnsantosDev for UX :-)

**Comment by johnsantosDev** [comment]
Let me give it a look Team

**Comment by ElvisAns** [comment]
Maybe we also need to credit this guy https://codepen.io/claudiabdm/pen/XWgrqGr

**Comment by johnsantosDev** [comment]
Team, I tested this and the flow, works realy fine, just some very minor ui improvments related to the alignments. 

1. Enable two factor authentication text is very far from the checkbox, users will think the switch is for the text update your settings...
2. we are using 2 columns here(good idea) but it's giving poor ui by making the left side empty.
I suggest to have the switch, the QR and the text "if you can't ..... " at the left column and the section starting with "the following backup codes can ... " at the right. 

WDYT @Yannick243 ? 


![Screenshot from 2023-11-13 01-02-54](https://github.com/cypht-org/cypht/assets/92297941/802fe014-5d73-417c-a9e1-da2cebf48e72)

**Comment by Yannick243** [comment]
Hello @johnsantosDev,
I have refactor the UI like this, what do you think ?

![CleanShot Nov 13 from imagecompressor](https://github.com/cypht-org/cypht/assets/14950700/e79bd6d1-f4f0-4fb5-bf72-47eec731090f)

**Comment by Yannick243** [comment]
Hello @ElvisAns,
can this be closed as it has been merged ?
