### ISSUE TITLE
start_page setting not saved

### ISSUE THREAD

**Issue by tracer9k** [cypht-org/cypht#783]
## Bugreport
start_page setting is not saved in a brand new installation and always gets default to none. Other settings get stored. Is it perhaps due to input validation? PHP 7.4.33 with mysql storage of settings. I can't upgrade php for now as other legacy applications are running don't support newer php versions very well.

the id of the default_sort_order setting is also start_page, could it be because of that?

**Comment by marclaporte** [comment]
@kambereBr Can you reproduce this on latest 1.4.x or master?

**Comment by marclaporte** [comment]
@Yannick243 Can you reproduce this on Cypht 1.4.x or master?

**Comment by Yannick243** [comment]
Hello @tracer9k,
Are you OK with this fix ?

**Comment by marclaporte** [comment]
@tracer9k Please re-open if it's not fixed.
