### ISSUE TITLE
Migrate from erusev/parsedown to league/commonmark

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#790]
Now: https://packagist.org/packages/erusev/parsedown

I want us to move to https://packagist.org/packages/league/commonmark

Why?
Tiki developers (who contribute a lot to Cypht) are experienced with league/commonmark: https://doc.tiki.org/Tiki-Flavored-Markdown

So in general, it makes sense to harmonize for the dependencies.

Both packages are popular and maintained. However, league/commonmark has more sub-depedencies. Not an issue for Tiki, but Cypht tries to be more lightweight.

**Comment by kroky** [comment]
It would add just a couple more composer packages to the vendor dir. Doesn't seem a big change. Also, Cypht currently uses Parsedown in just one place, so replacing will be easy.

**Comment by kambereBr** [comment]
Here is the Pull Request : https://github.com/cypht-org/cypht/pull/812

**Comment by marclaporte** [comment]
league/commonmark is much more active:
https://openhub.net/p/_compare?project_0=league%2Fcommonmark+%28PHP%29&project_1=parsedown
