### ISSUE TITLE
Plain text shows as attachment

### ISSUE THREAD

**Issue by ulfgebhardt** [cypht-org/cypht#794]
## 🐛 Bugreport

![image](https://github.com/cypht-org/cypht/assets/1238238/d1ae0b93-1e55-4c38-aa80-2b65f58ad062)

When sending plain text emails to oneself the text is shown as attachment while it is just the message itself.
This is a regression compared to before (2021).

This is how those emails looked before

![image](https://github.com/cypht-org/cypht/assets/1238238/95eb1690-6e79-44f5-8198-7f783c11fb7c)
(this was sent for a cypht version of 2021)

### Version & Environment

Rev: https://github.com/cypht-org/cypht/commit/a5285756aff89bf1ee85cffa7fea2a6fd9b132ce

OS:  [chrome-latest] - more details where this runs if needed

### Steps to reproduce
1. Send plain text email to oneself
2. receive email attachment symbol
3. wonder where the attachment is
4. ...
5. Profit

**Comment by marclaporte** [comment]
Thank you @ulfgebhardt for taking the time to compare with a 2021 version to confirm the change of behavior.

**Comment by marclaporte** [comment]
Could this be related to this? https://github.com/cypht-org/cypht/pull/735

**Comment by kroky** [comment]
I think it is related to https://github.com/cypht-org/cypht/pull/661

**Comment by ulfgebhardt** [comment]
This is the commit I have checked out where everything is still fine. The change must have been introduced after this:
https://github.com/cypht-org/cypht/commit/02ddf0d10e4fc304e8e07dad8700bf33a739071d

**Comment by marclaporte** [comment]
@ulfgebhardt  Can you confirm that this fixed it? https://github.com/cypht-org/cypht/pull/815
