### ISSUE TITLE
Menu icons broken in dark mode themes

### ISSUE THREAD

**Issue by jasonmunro** [cypht-org/cypht#795]
## 🐛 Bugreport
Trash, Junk, and Drafts menu icons broken in dark themes

### Version & Environment
master as of today

### Steps to reproduce
1. Load a dark theme
2. observe the menu
3.
4. ...
5. Profit

Dark themes inject a path attribute into icon SVG strings to alter the color to match the theme. Icons added to lib/output.php need to be added to the list in modules/themes/modules.php to have their colors altered (this is because we don't want to blindly alter all of the icons).  For 2 of these icons that are currently broken they are defined as pngs which means they will never work properly (they must be non-binary svgs). The third (trash) is an svg but still is not working they way the rest do.

**Comment by jasonmunro** [comment]
![menu](https://github.com/cypht-org/cypht/assets/3793556/fdae682a-ff3f-430b-860f-a5b3af3daeb7)

**Comment by marclaporte** [comment]
Thank you @jasonmunro 

These are 3 new item elements and we never tested with a dark theme

We will fix soon

**Comment by marclaporte** [comment]
@jasonmunro Is the fix OK?

**Comment by jasonmunro** [comment]
yep this is fixed, thanks!
