### ISSUE TITLE
have combined Inbox

### ISSUE THREAD

**Issue by apezio** [cypht-org/cypht#797]
## 🚀 Feature
Combined Inbox

There is "Everything" which is useful to browse or search, everything. 
There is Unread - but that's not very useful when I want to keep an eye on what emails I am addressing/working on.

I basically spend 90% of my time when using email at the Inbox page - but Cypht doesn't seem to have one?

I end up doing Email -> Account -> Inbox (three clicks to see my mail)
but if I have more than one account, I have to switch back and forth between Inboxes.

I feel like i'm missing something obvious here.  

I could probably figure out how to copy the code for "Everything" and only apply it to imap folders with the name Inbox...

**Comment by marclaporte** [comment]
There is a combined inbox indeed: https://cypht.org/documentation.html

**Comment by marclaporte** [comment]
In each inbox, there is a button to "add/remove folder from combined pages"

**Comment by marclaporte** [comment]
@apezio

**Comment by apezio** [comment]
I guess I should have included a picture - there's literally no "Inbox" in the menu of mailboxes.  I have moved on to snappymail an deleted my cypht install.

**Comment by marclaporte** [comment]
<img width="771" alt="2023-11-03-Cypht-add-this-folder-to-combined-pages" src="https://github.com/cypht-org/cypht/assets/1004261/cfa108fb-3e74-43f2-8a34-0db23d5ac0e9">
