### ISSUE TITLE
Test Cypht with PHP 8.2 and 8.3

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#829]
Fix all issues in master (future Cypht 1.5.x or 2.0)
Backport critical fixes to Cypht 1.4.x

**Comment by marclaporte** [comment]
@mijofa mentioned an issue here: https://github.com/cypht-org/cypht/issues/405#issuecomment-1818119396

**Comment by Shadow243** [comment]
Cypht is functioning correctly with PHP 8.2 & 8.3, some deprecations are solved by  [#830](https://github.com/cypht-org/cypht/pull/830)

**Comment by marclaporte** [comment]
Thank you @Shadow243
