### ISSUE TITLE
Unable to install ext-PDO with Composer.

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#836]
## 🐛 Bugreport

Unable to use composer to install ext-PDO for database connections.  Composer acts like ext-PDO is already installed, but still suggests that it be installed.  I've also tried installing Postgres and Maria, with all their dependencies, and what I think are all the available php modules that connect to either Maria or Postgres.  I also don't know if Composer is just lying, and a database connection would still work.  (If I uncomment the database extension lines in php.ini, Composer says that PDO is already enabled, even though it still says that ext-PDO is suggested.)

### Version & Environment

Rev: a8d6826 (Latest master as of December 5, 2023.)

OS:  Debian 12.2..0
PHP 8.2.7
Composer: 2.5.5

### Steps to reproduce
1. Install some fresh Debian
2. As root: apt install php composer php-curl php-redis php-gd php-memcached php-gnupg php-imagick php-bcmath php-soap php-xdebug php-xml
3. mkdir cypht-test
4. cd cypht-test
5. wget https://github.com/cypht-org/cypht/archive/master.zip
6. unzip master.zip
7. cd cypht-master
8. composer suggest <-- this shows that ext-PDO is not installed
9. composer require ext-PDO <-- this installs a bunch of stuff, then throws into a bunch of looping "composer suggest" commands.
10. composer suggest <-- still shows that ext-PDO is not installed.

**Comment by Yannick243** [comment]
This has been adjusted in the Composer suggestions; however, you should just ensure that the different modules are installed before enabling the extensions in php.ini for MariaDB and/or PostgreSQL; 
```
apt install php8.2-mysql php8.2-pgsql
```

and finally check if the extension is enabled with `phpinfo();`
![phpinfo-screen](https://github.com/cypht-org/cypht/assets/14950700/b28e25dd-0865-4c89-bdc2-af7944d50ecb)

**Comment by marclaporte** [comment]
@PaulTGG Can we close this?

**Comment by PaulTGG** [comment]
Yep, my bad!
