### ISSUE TITLE
HTML to text process is broken (fix included)

### ISSUE THREAD

**Issue by jasonmunro** [cypht-org/cypht#850]
We use a custom class to convert HTML to text specifically when sending outbound mail so we have both the "fancy" version and the plain text version of the message.  Last month a line in that class was changed to avoid a deprecation warning however it was changed to the wrong replacement function resulting in a bunch of decoded html entities in plain text inserted into the output.  The following fixes the bug and avoids the original deprecation warning:

```
diff --git a/modules/core/message_functions.php b/modules/core/message_functions.php
index 8f922515..86cfe81b 100644
--- a/modules/core/message_functions.php
+++ b/modules/core/message_functions.php
@@ -435,7 +435,7 @@ class HTMLToText {

     function __construct($html) {
         $doc = new DOMDocument();
-        $doc->loadHTML(htmlentities($html, ENT_QUOTES | ENT_HTML5, 'UTF-8'));
+        $doc->loadHTML(html_entity_decode($html, ENT_QUOTES | ENT_HTML5, 'UTF-8'));
         if (trim($html) && $doc->hasChildNodes()) {
             $this->parse_nodes($doc->childNodes);
         }
```

**Comment by Shadow243** [comment]
I'm trying to find that commit but according to this: [https://github.com/cypht-org/cypht/commit/811966cba0dc7ec935310c06fa32498fc134de38#diff-fb847a047f39596c5eb56b8d842486eec3cc7cc15a7aa2417dd6cf8625da75e4](https://github.com/cypht-org/cypht/commit/811966cba0dc7ec935310c06fa32498fc134de38#diff-fb847a047f39596c5eb56b8d842486eec3cc7cc15a7aa2417dd6cf8625da75e4) it should be
```
    function __construct($html) {
        $doc = new DOMDocument();
-       $doc->loadHTML(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'));
+       $doc->loadHTML(htmlentities($html, ENT_QUOTES | ENT_HTML5, 'UTF-8'));
        if (trim($html) && $doc->hasChildNodes()) {
            $this->parse_nodes($doc->childNodes);
        }
```

I'm looking for that commit to have an idea about why it has been changed to html_entity_decode

**Comment by jasonmunro** [comment]
the commit you are referencing did 2 things:

1. it fixed the deprecation warning about using mb_convert_encoding()
2. it broke the output. It should NOT be htmlentities, it should be html_entity_decode

the diff I pasted is what I suggest we do to fix the problem :)

**Comment by Shadow243** [comment]
Copy that @jasonmunro, I apply the suggestion right now.

**Comment by jasonmunro** [comment]
for example, if we feed that class the following HTML:

`&gt; &lt; <p>FOO</p> <p>BAR</p><br /> &quot;'`

It will output the following:

`&gt&semi; &lt&semi; FOO BAR &quot&semi;`

this is not a nice text representation of the html :) If we switch htmlentities to html_entity_decode we get the desired output:

```
> <
FOO
BAR
"
```

**Comment by Shadow243** [comment]
https://github.com/cypht-org/cypht/pull/851
