### ISSUE TITLE
Option to always allow external images

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#861]
## 🗣 Suggestion
This may fly in the face of security, but it would be nice if there was an option to "always show inline images."  At number of email senders use inline images (whether for simple header images, formatting purposes, aesthetic reasons, or, more importantly, for confirmation buttons, or action buttons that users have to click), so it would be nice to have an option where the user can accept the risks involved, and just let the images appear for all their mail.

**Comment by marclaporte** [comment]
Brainstorming a few options:
* Never permit external images (the default)
* Permit external images for this email (an option now)
* Permit external images from known senders (a reasonable enhancement)
* Permit external images per image source (This could be a lot of work)
* Permit all external images (Opens invasion of privacy)

**Comment by marclaporte** [comment]
For confirmation buttons, or action buttons that users have to click: I noticed that Roundcube deals with this better: They show where the image is, so you know where to click even if the image is not loaded. Cypht should do this as well.

**Comment by PaulTGG** [comment]
I think your third option is best - something like "Always allow images from this sender."

> Brainstorming a few options:
> 
>     * Never permit external images (the default)
> 
>     * Permit external images for this email (an option now)
> 
>     * Permit external images from known senders (a reasonable enhancement)
> 
>     * Permit external images per image source (This could be a lot of work)
> 
>     * Permit all external images (Opens invasion of privacy)

**Comment by marclaporte** [comment]
> For confirmation buttons, or action buttons that users have to click: I noticed that Roundcube deals with this better: They show where the image is, so you know where to click even if the image is not loaded. Cypht should do this as well.

Spin off: https://github.com/cypht-org/cypht/issues/865

**Comment by marclaporte** [comment]
Please make it nicer visually and clearer for end user what is the security/privacy concern.

![2024-01-17_095324](https://github.com/cypht-org/cypht/assets/1004261/c6f49449-f790-4189-aa6a-726f656a79ee)

**Comment by marclaporte** [comment]
Please make a list of each external ressource, and permit that we approve them individually, with an option to approve all if there is more than one.
