### ISSUE TITLE
Option to move back to mailbox after performing message action

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#862]
## 🗣 Suggestion
I don't even know how feasible this would be, but it'd be nice to have the option to go back to the mailbox after performing an action on a message, such as deleting or moving a message, or marking the message as unread.  Right now, the default behaviour is to move to the next message in the mailbox (unless you're viewing messages inline), which can cause the second message to be marked as read.  (I know that a partial workaround is to select "Don't flag a message as read on open", but if you're viewing an email, there's no way to mark that email as being "read" - you have to mark it as read from the mailbox view!)

**Comment by marclaporte** [comment]
@Yannick243 Please research and advise. I think this options exists somewhere.

**Comment by marclaporte** [comment]
Related: https://github.com/cypht-org/cypht/issues/435

**Comment by Yannick243** [comment]
After conducting research, I realized that this question had indeed been discussed earlier. 
However, the related option is missing in the preferences. 
The preference that had been worked on was to be able to display the Next & Previous email buttons while being in the view mode of an email.
I believe we should add a preference to determine whether the user wants to go to the view mode of the next email or move back to mailbox after performing message actions.

Preferences page:
![preference-btn](https://github.com/cypht-org/cypht/assets/14950700/42dbd520-f81f-4a23-ba73-9529a3a3e487)

Email preview:
![next-prev-btn](https://github.com/cypht-org/cypht/assets/14950700/f3d67d45-62d4-432e-ae99-c5e496b78de1)

**Comment by Yannick243** [comment]
The issue has been fixed: [https://github.com/cypht-org/cypht/pull/896](https://github.com/cypht-org/cypht/pull/896)

Here is the related setting in Cypht:
![CleanShot 2024-02-16 at 11 42 05](https://github.com/cypht-org/cypht/assets/14950700/0a6ac5cd-7d44-40a1-a454-3fee914bb752)

**Comment by Yannick243** [comment]
Yes it works even if the other setting is de-activated, it also work for all the various lists except the sent folder for now. 
I am trying to figure out why it doesn't work for that folder.

**Comment by PaulTGG** [comment]
Closing as per https://github.com/cypht-org/cypht/pull/896.  I'll be able to do more testing once the code base is a little more stable.
