### ISSUE TITLE
Add a simpler way to show source of an email (Like in Roundcube)

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#871]
![2024-01-17_101902](https://github.com/cypht-org/cypht/assets/1004261/adedd648-4f50-49ac-8086-a7d37385f8ea)

**Comment by marclaporte** [comment]
@jacob-js I like this!

I see the source, and I have a link to download or copy to clipboard. Can we have a way to return to the email?

**Comment by jacob-js** [comment]
> @jacob-js I like this!
> 
> I see the source, and I have a link to download or copy to clipboard. Can we have a way to return to the email?

@marclaporte in case you didn't notice, the source is opened in a new tab, leaving the email tab safe. I just think that in case the user wants to go back, they can close the newly opened tab via the close button provided by the browser. Reimplementing this on the page would be an unnecessary overload. Does this resonate well with you?

**Comment by marclaporte** [comment]
Makes sense. Closing.
