### ISSUE TITLE
ldap_contacts module needs update after latest .env migration

### ISSUE THREAD

**Issue by kroky** [cypht-org/cypht#875]
## 🐛 Bugreport
ldap_contacts->modules file addresses ldap_config as a series of configuration arrays from different sources. Latest .env migration makes that a single array and thus introducing fatal 500 errors. See settings page in latest master with ldap_contacts allowed, for example.

### Version & Environment
Master

**Comment by kroky** [comment]
@Shadow243 it will be best for you to take a look as you did the original .env integration.

**Comment by Shadow243** [comment]
Solved.
