### ISSUE TITLE
Links not opening in a new window/tab after #859

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#877]
## 🐛 Bugreport
Links not opening in a new window/tab after https://github.com/cypht-org/cypht/pull/859 was completed.  The `target="_blank" rel="noopener"`  is not showing up on external links (not to github links, at least).

### Version & Environment
4f2eae309b6703eed9b04486040573c1785f19c9
OS:  Debian 12.4, PHP 8.2.7

### Steps to reproduce
1. Install some fresh Debian, add dependencies, install Cypht as per instructions.
2. Try clicking an external link in an email (e.g., a github link).  The link opens in the current window.
![linksinnewwindow](https://github.com/cypht-org/cypht/assets/12187131/b35d9b5e-ea29-408c-8d73-82bfe3e5b81b)

**Comment by Yannick243** [comment]
Hello @PaulTGG, thank you for reporting that. 
I'm trying to reproduce the issue, and I'll get back to you shortly.

**Comment by Yannick243** [comment]
PR: [https://github.com/cypht-org/cypht/pull/883](https://github.com/cypht-org/cypht/pull/883)

**Comment by Yannick243** [comment]
Hello @PaulTGG ,
The pull request has been merged, kindly confirm on your side.

**Comment by PaulTGG** [comment]
Looks good to me.  target=_blank" is showing on external links.
![Screenshot_2024-02-07_21-51-11](https://github.com/cypht-org/cypht/assets/12187131/b0548091-3173-4516-8772-f8a3b5f25a0d)
