### ISSUE TITLE
Emails only showing up using debug site after installing 4f2eae3

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#878]
## 🐛 Bugreport
I upgraded to 4f2eae3 today, and no emails are showing up when using the default site view.  Also, the IMAP folders don't show up if you expand the account folders.  Both features work when using the debug site.

### Version & Environment
4f2eae3
OS:  Debian 12.4, PHP 8.2.7

### Steps to reproduce
1. Update Cypht to the latest master (as of Jan 30)
2. Emails and IMAP folders show up in the debug site, but not it the normal site.

**Comment by kroky** [comment]
Did you run composer install  and config_gen again? Working with master branch means doing config updates, clearing caches and other maintenance work quite often as we are currently merging a lot of MRs to stabilize Cypht before 2.0 release.

**Comment by PaulTGG** [comment]
> Did you run composer install and config_gen again? Working with master branch means doing config updates, clearing caches and other maintenance work quite often as we are currently merging a lot of MRs to stabilize Cypht before 2.0 release.

Yes, both.  The only thing that was the same from my previous install was the user settings (which are in a DB).  All the other instructions were followed as if it was a brand-new install.  It just seemed strange to me that debug should work and "regular" wouldn't.  That said, if this seems like something that may have come from all the merges happening right now, just say the word, and I'll close this issue, and test it again when Cypht is closer to 2.0!

**Comment by Shadow243** [comment]
I'm trying to reproduce it on a Debian 12 server with the same PHP version to see if I'll get the same error.

> > Did you run composer install and config_gen again? Working with master branch means doing config updates, clearing caches and other maintenance work quite often as we are currently merging a lot of MRs to stabilize Cypht before 2.0 release.
> 
> Yes, both. The only thing that was the same from my previous install was the user settings (which are in a DB). All the other instructions were followed as if it was a brand-new install. It just seemed strange to me that debug should work and "regular" wouldn't. That said, if this seems like something that may have come from all the merges happening right now, just say the word, and I'll close this issue, and test it again when Cypht is closer to 2.0!

**Comment by kroky** [comment]
Please keep this issue open - we need to find out the reason. It is just that I cannot reproduce... maybe you can send some env/debugging info to help reproduce? Any errors in browser's console, any debugging messages you see?

**Comment by PaulTGG** [comment]
> Please keep this issue open - we need to find out the reason. It is just that I cannot reproduce... maybe you can send some env/debugging info to help reproduce? Any errors in browser's console, any debugging messages you see?

I just tested with a fresh install of Debian, and the latest master.  When using the normal site, and looking at "Everything," the browser console says this: `Uncaught ReferenceError: Sortable is not defined
    <anonymous> http://172.16.32.254/mail/site.js?v=EdefVEVoNrXqf0tvckSlKaPIFCVYAsZBwbFwqrvJ3rw=:2156`.  So such message using the debug site.  Also, there are no Apache error logs when using the normal site.

My .env file is here: https://pastebin.com/4m8iXFWx

**Comment by kroky** [comment]
@PaulTGG thanks for the info.
@Shadow243 put index.php DEBUG_MODE to false and you will see the issue. When we bundle site.js with all js files, we are not adding the third party libs anymore - thus Sortable is not defined error.

**Comment by Shadow243** [comment]
Solved by: [https://github.com/cypht-org/cypht/pull/881](https://github.com/cypht-org/cypht/pull/881)
