### ISSUE TITLE
Release Cypht 2.0

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/cypht#879]
After 1.4.x, we will go to 2.0 because there are many big changes.

The main ones:

- https://github.com/cypht-org/cypht/pull/828
- https://github.com/cypht-org/cypht/pull/625
- https://github.com/cypht-org/cypht/pull/855

So let's clean this out: https://github.com/cypht-org/cypht/pulls, stabilize and release!

**Comment by marclaporte** [comment]
Two blockers for Cypht 2.0:
- https://github.com/cypht-org/cypht/pull/855
- https://github.com/cypht-org/cypht/pull/921

**Comment by marclaporte** [comment]
Also, we plan to have JMAP working for the basics: https://github.com/cypht-org/cypht/issues/180

And some more advanced features will be for later (ex.: Cypht 2.1)
https://github.com/cypht-org/cypht/issues/931

**Comment by marclaporte** [comment]
The milestones are done except for JMAP: https://github.com/cypht-org/cypht/milestone/2

We have 4 non-draft MRs that it would make sense to add:
https://github.com/cypht-org/cypht/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse

**Comment by ConnectGrid** [comment]
This is exciting! Thanks for your hard work on this!

**Comment by marclaporte** [comment]
We have 6 non-draft MRs that it would make sense to add:
https://github.com/cypht-org/cypht/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse

**Comment by marclaporte** [comment]
@josaphatim @kroky Let's clean this list and release 2.0
https://github.com/cypht-org/cypht/issues/879

**Comment by marclaporte** [comment]
The remaining PRs are not blockers so we can release Cypht 2.0 any time!

**Comment by Baraka24** [comment]
> The remaining PRs are not blockers so we can release Cypht 2.0 any time!

We are now experiencing Cypht 2.0 for  good notes.

**Comment by marclaporte** [comment]
I did a round of testing on Cypht master, and I can tell you there is a huge number of "paper cut bugs"
https://en.wikipedia.org/wiki/Paper_cut_bug

Why it is buggy:
- We added tons of new features since 1.4.x
- Major changes like moving to Bootstrap 5 and new account interface
- Most recently active developers are new to the code base
- We don't yet have a good dev/testing/qa feeback loop (we'll work on this later)

So 2.0 will be buggy. How will we stabilize things in the coming months with 2.1, 2.2, 2.3, etc.?
- 6 to 8 developers will be assigned to work part time on Cypht for at least the next 8 months. They are pretty new to Cypht, so it will be a learning experience, and to improve our development capacity for future versions.
- This team **will fix all appropriately reported paper cut bugs**, and fix the non-paper cut bugs according to priorities (Is it easy to fix, is it a commonly-used feature, etc.)

**Comment by kroky** [comment]
Cypht 2.0 is out:
https://github.com/cypht-org/cypht/releases/tag/v2.0.0

Commit messages matter, wow - I'd never be able to generate such a nice changelog text. Nicely done mentioning all the contributors as well.

@marclaporte, feel free to describe the bigger changes in more detail on the top of the release message.

**Comment by marclaporte** [comment]
> @marclaporte, feel free to describe the bigger changes in more detail on the top of the release message.

Done

**Comment by marclaporte** [comment]
> Commit messages matter, wow - I'd never be able to generate such a nice changelog text. Nicely done mentioning all the contributors as well.

Indeed! Which script does this?

**Comment by tarasis** [comment]
It’s been Interesting to follow the release, and I hope to be able to contribute in future at least for CSS (I know little to no php).

for the release notes, it was great that everyone was credited. it would be useful though to separate fixes from features. 

I know it’s more effort (I’d be happy to do it if you eanted), but as a user it’s much more helpful to be able to look and seen the new features, then the fixes rather than have them interspersed

**Comment by marclaporte** [comment]
@tarasis Thank you for the kind words.

1. We have tons of CSS work to do given the move to Bootstrap 5. Your help is most appreciated.
2. I improved https://github.com/cypht-org/cypht/releases/tag/v2.0.0 to have a section for "Main changes". You are welcome to separate fixes from features, but I warn you that it's a lot of work. And there are ambiguous one. Ex.: A fix on a recently added feature. Is it a fix? Or just part of the new feature?

**Comment by kroky** [comment]
It is just a github feature aggregating all commit messages from previous tag. I think if developers add a bit of semantics to the commit messages like [ENH], [FEAT] and [FIX], it will be quite easy to aggregate the release notes by feature, enhancement or a fix.

**Comment by marclaporte** [comment]
> So 2.0 will be buggy.

I just officialized that Cypht 1.4.x is now an LTS version so end users don't have to rush to upgrade:
https://github.com/cypht-org/cypht/wiki/Lifecycle

**Comment by marclaporte** [comment]
Cypht 2.0.1 with a bunch of bug fixes: https://github.com/cypht-org/cypht/releases/tag/v2.0.1

**Comment by marclaporte** [comment]
Cypht 2.2.0: https://github.com/cypht-org/cypht/releases/tag/v2.2.0

**Comment by marclaporte** [comment]
Cypht 2.3.0: https://github.com/cypht-org/cypht/releases/tag/v2.3.0
