### ISSUE TITLE
A "remark" field to remember why you added a profile

### ISSUE THREAD

**Issue by w-b-k** [cypht-org/cypht#882]
## 🗣 Suggestion

I create a mail alias and a corresponding identity/profile per organization/entity/contact  that I deal with, to isolate data leaks and prevent merging of profiles in different providers' back-ends. 
The aliases are not very self-explanatory, so I keep notes which alias goes with which entity. 

For me it would be helpful to have a "remarks" field in addition to the "signature" field when managing profiles. Is it too much a niche application of aliases/profiles to have any merit outside of my application, or would it be something useful for a wider audience? 

Thank you for your consideration!

**Comment by marclaporte** [comment]
@w-b-k I Iike it. Let's do it.

**Comment by marclaporte** [comment]
@IrAlfred Please show us your skills :-)

**Comment by marclaporte** [comment]
@w-b-k: looking at this more: 

There are two text fields:
* Display Name
* Signature

What would be negative about using the Display Name?

**Comment by IrAlfred** [comment]
> @IrAlfred Please show us your skills :-)

Not sure to understand well what this is about, please I need more details

**Comment by w-b-k** [comment]
Hi, thanks for your prompt response ! :-)

> What would be negative about using the Display Name?

Is the display name not the field that is sent as "My Name" to the recipient of the email? 

I would write something like "added this alias for exchange with the piano teacher; starting 20240103". If "Display name" is not sent as "My Name" with the email, is another field used to supply the recipient with my name?

**Comment by marclaporte** [comment]
@w-b-k Good point. Please test, and if Display Name is used as you said, we'll add one more field.

**Comment by marclaporte** [comment]
@IrAlfred https://github.com/cypht-org/cypht/tree/master/modules/profiles

**Comment by w-b-k** [comment]
> @w-b-k Good point. Please test, and if Display Name is used as you said, we'll add one more field.

Tested. The text entered in the "Display name" field is displayed in Cypht when sending a new message (below the field for typing the message, a combobox to select the from-identity). 

In the receiving mail client, the text is displayed as the 'friendly name' in combination with the email address. 

> > @IrAlfred Please show us your skills :-)
> 
> Not sure to understand well what this is about, please I need more details

I got there by cilcking Profiles under Settings: 

![image](https://github.com/cypht-org/cypht/assets/27885942/89916d64-50fc-4cf1-8a57-7664f4282ae1)

When adding (or editing) a profile, the confusion was about the "Display name" field: 

![image](https://github.com/cypht-org/cypht/assets/27885942/e8576614-64f4-4056-a705-4e0b07d32aa6)

I'd like to have an option to write some remarks about why I added the particular profile: 

![image](https://github.com/cypht-org/cypht/assets/27885942/236b090e-0279-4643-84c8-50d3afc29428)

(In a perfect world the field would be multi line, or a wider letter box :-P )

**Comment by IrAlfred** [comment]
Okay, thanks

**Comment by marclaporte** [comment]
@w-b-k Can you please test? https://github.com/cypht-org/cypht/pull/903

**Comment by w-b-k** [comment]
Hi Alfred & Marc, 

Thank you, looks (and works, on first test) great! 

A small non-functional remark on the changes in modules.php : in most places the rmk is added after sig, but in a cases it is added on a different position, for example on [line 129](https://github.com/cypht-org/cypht/pull/903/files#diff-2375a5d259659c96bfacd4c4e717655616a0e7afe58f398934baec685572cc1fR129) it follows 'type', instead of 'sig' (at line 121). Is that on purpose?

**Comment by IrAlfred** [comment]
Thank you for your feedback. Regarding the non-functional remark concerning the position of rmk in the module.php file compared to its position in other places, this was not done on purpose but just that we didn't pay too much attention to it . I fix that for good harmony.

**Comment by marclaporte** [comment]
> I noticed the new files being quite different from the ones I had installed (1.4.1, via Yunohost; what is the current version?)

Cypht 1.4.1 is the current stable version. Because of major changes in master, the next release will be 2.0

**Comment by marclaporte** [comment]
@w-b-k Is the latest code good to merge?
