### ISSUE TITLE
hm3.sample.ini file is missing

### ISSUE THREAD

**Issue by devmin222** [cypht-org/cypht#893]
## 🐛 Bugreport
When trying to install, the hm3.ini sample file is not found on the repo

### Version & Environment
2c635a48a4559b6efbba90d3e49bca310672bb39

**Comment by Shadow243** [comment]
Thank you @devmin222  for this clarification.

The master branch no longer supports hm3.ini, but if you clone for example the 1.4.x branch which still supports hm3.ini you will have the hm3.sample.ini file. The latter has been replaced by .env.example.

The documentation will take this update into account: https://github.com/cypht-org/cypht-website/pull/49

**Comment by devmin222** [comment]
Alright got it thanks!
