### ISSUE TITLE
Hm_Notices ins't showing any alert

### ISSUE THREAD

**Issue by jacob-js** [cypht-org/cypht#919]
In the past, invoking the `show()` method of Hm_Notices with a message as an argument would trigger an alert for the user. This occurred when a message was moved, copied to a new folder, or deleted. While these are minor use cases I'm aware of, this function is frequently utilized throughout the codebase, yet none of its occurrences currently result in displaying an alert.

**Comment by kroky** [comment]
@alvinBM @josaphatim probably a regression from the bootstrap move?

**Comment by josaphatim** [comment]
@kroky @jacob-js There is a PR for that thanks. https://github.com/cypht-org/cypht/pull/905

**Comment by marclaporte** [comment]
@jacob-js please advise

**Comment by jacob-js** [comment]
Thank you for the fix @alvinBM
