### ISSUE TITLE
Can't return back to the same page after logout

### ISSUE THREAD

**Issue by josaphatim** [cypht-org/cypht#928]
## 🐛 Bugreport
Before https://github.com/cypht-org/cypht/pull/625 we were able to come back to the same page (mainly pages containing an id as other pages are still working). With unique ids this feature is broken getting a server error because the id can't be found.

https://github.com/cypht-org/cypht/assets/80334370/7129f8a8-e21d-4150-8f4f-cd0b008a095c

**Comment by marclaporte** [comment]
Is it related to this?
https://github.com/cypht-org/cypht/pull/941

**Comment by josaphatim** [comment]
> Is it related to this? #941

Not related

**Comment by Yannick243** [comment]
Fixed here [https://github.com/cypht-org/cypht/pull/1123](https://github.com/cypht-org/cypht/pull/1123)
