### ISSUE TITLE
 Attempt to perform actions (delete, test, hide, forget) Buttons not working on servers page

### ISSUE THREAD

**Issue by Shadow243** [cypht-org/cypht#937]
## Steps to Reproduce
1. Connect to a server.
2. Navigate to the server details page.
3. Attempt to perform actions (delete, test, hide, forget) using the respective buttons.
4. Note the outcome or error encountered.

## Expected Behavior
Actions (delete, test, hide, forget) should be successfully executed without errors when performed on a connected server.

## Actual Behavior
The action buttons for connected servers do not function as expected.

**Comment by Shadow243** [comment]
PR: [https://github.com/cypht-org/cypht/pull/936](https://github.com/cypht-org/cypht/pull/936)

**Comment by marclaporte** [comment]
This has been merged.
