### ISSUE TITLE
composer create-project installing older version

### ISSUE THREAD

**Issue by ConnectGrid** [cypht-org/cypht#940]
## 🐛 Bugreport

Running `composer require jason-munro/cypht` installs the latest version (1.4.1 at time of this writing). However, calling `composer create-project jason-munro/cypht` is installing v1.4.0, which has outdated dependencies that don't support PHP 8.3.x.

I'm not familiar with enough the `create-project` command to know how to fix this.

### Version & Environment

Rev: []

OS:  []

### Steps to reproduce
1. Run `composer create-project jason-munro/cypht`

On PHP 8.3, dependency validation fails.

**Comment by marclaporte** [comment]
@christer77 has volunteered on this one.

**Comment by Shadow243** [comment]
@ConnectGrid It could be due to caching.

Did you try this:`composer clear-cache` and then `composer create-project jason-munro/cypht` ??

**Comment by marclaporte** [comment]
> On PHP 8.3, dependency validation fails.

What is the exact error message?

Cypht 1.4.x supports minimum PHP 5.6
Cypht 2.0.x (soon to be released) supports minimum PHP 7.4

It could be a pain to support PHP 5.6 to PHP 8.4 so we may want to put a max PHP version for Cypht 1.4

Can you try Cypht master? We did some work to support PHP 7.4 to PHP 8.4

**Comment by christer77** [comment]
ERROR MESSAGE :
The error is not related to cypht but to the htmlpurifier package which was fixed to "^4.13" while this version does not support php 8.3.x, so since 2022-09-16 to fix some bugs including php 8.3.x support [htmlpurifier-releases](https://github.com/ezyang/htmlpurifier/releases)

**Comment by christer77** [comment]
ERROR MESSAGE :
![cypht-jason-munro-error](https://github.com/cypht-org/cypht/assets/62720246/d9d75d8a-b4b9-497b-b01f-fe6a70c8b6bd)

**Comment by marclaporte** [comment]
ok, so the next version of HTML Purifier will support PHP 8.4
https://github.com/ezyang/htmlpurifier/pull/396

**Comment by christer77** [comment]
Exactly, and this since version 4.17, this means that I am returning the PR because [this](https://github.com/cypht-org/cypht/pull/943) of which is 4.16 is limited to 8.3

**Comment by marclaporte** [comment]
@christer77 You need to generate a composer.lock file as well.

**Comment by christer77** [comment]
It's noted @marclaporte

**Comment by marclaporte** [comment]
@christer77 please see comments for https://github.com/cypht-org/cypht/pull/943

**Comment by christer77** [comment]
Consideration of comments [#943 ] in [PR](https://github.com/cypht-org/cypht/pull/971)
