### ISSUE TITLE
Can not translate `Junk` or `Trash`.

### ISSUE THREAD

**Issue by PJ-568** [cypht-org/cypht#956]
## 🐛 Bugreport
Is it possible to apply translate to these?
I could not find `Junk` or `Trash` in array in `language/*`.
![Can not tanslate](https://github.com/cypht-org/cypht/assets/63788100/37e97a51-2e9a-42e1-8dd4-77e09a4eeaad)

### Steps to reproduce
N/A

**Comment by PJ-568** [comment]
And another question, it says that `DEFAULT_LANGUAGE's Valid values are 2 character langauge codes that have matching language definitions in the language/ folder`. So I set `DEFAULT_LANGUAGE` as `cn`, it did not work.

So it should be `cn`? Or `zh-CN`?  Or `zh-Hans`, since the filename in `language/` folder is `zh-Hans.php`?

**Comment by josaphatim** [comment]
> DEFAULT_LANGUAGE

DEFAULT_LANGUAGE=zh-Hans

This works

**Comment by josaphatim** [comment]
> ## 🐛 Bugreport
> Is it possible to apply translate to these? I could not find `Junk` or `Trash` in array in `language/*`. ![Can not tanslate](https://private-user-images.githubusercontent.com/63788100/322774468-37e97a51-2e9a-42e1-8dd4-77e09a4eeaad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjA1NTAsIm5iZiI6MTcxMzI2MDI1MCwicGF0aCI6Ii82Mzc4ODEwMC8zMjI3NzQ0NjgtMzdlOTdhNTEtMmU5YS00MmUxLThkZDQtNzdlMDlhNGVlYWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA5MzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTcxOWM2NzkxYzE4N2YzYmYyM2VkMmMxMGRlOTQyNTYxMzc2YjQxMWFmMzlhYTAwMDg0N2VkNjY1NDg5MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AIzYW6Rqy1CHNbs1o-_sozU1WF_MgeEBV4Wwa8UvBnc)
> 
> ### Steps to reproduce
> N/A

You can now create a pull request with translation of Trash and Junk

**Comment by PJ-568** [comment]
> ## 🐛 Bugreport
> 
> Is it possible to apply translate to these? I could not find `Junk` or `Trash` in array in `language/*`. ![Can not tanslate](https://private-user-images.githubusercontent.com/63788100/322774468-37e97a51-2e9a-42e1-8dd4-77e09a4eeaad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjA1ODksIm5iZiI6MTcxMzI2MDI4OSwicGF0aCI6Ii82Mzc4ODEwMC8zMjI3NzQ0NjgtMzdlOTdhNTEtMmU5YS00MmUxLThkZDQtNzdlMDlhNGVlYWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA5MzgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNzViYjMzNzA0ZGUwMDVjMzQxMDliOGUxOGRmMDE5MTBkY2Y1NTUyZmYwYzk4MGY1MzE4MTdmNzZkMzliOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i5NffvZRXDXvCO9QXJuJYfFFatn4ki7b62XYOd-NPfk)

Thank you, but how about this?
