### ISSUE TITLE
Hm, TM - what are these in reference to?

### ISSUE THREAD

**Issue by TheDigitalOrchard** [cypht-org/cypht#962]
## 💬 Question

Throughout the Cypht framework, there are classes prefixed with `Hm_`, and the Environment variables are stored with a prefix of `TM_`.

What are these in reference to? Legacy name? If so, can we deprecate these in favour of a `Cypht_ \ CYPHT_` prefix?

**Comment by marclaporte** [comment]
Context: https://github.com/cypht-org/cypht/issues/602

Yes, we should clean up!

If low risk, we sneak in 2.0, else 2.1 or 3.0

**Comment by Shadow243** [comment]
> @Shadow243 As you worked on #823 please opine.

This is an option to take into consideration, however there is too much refactoring to do because this will affect all cypht modules, unit tests, lib and certain javascript files.

I would therefore suggest doing this in a version other than 2.0 which must already be released asap.

**Comment by marclaporte** [comment]
> and the Environment variables are stored with a prefix of `TM_`.

@Shadow243 what does TM stand for?

**Comment by Shadow243** [comment]
> TM

The idea of putting dotenv came from tiki manager, this TM surely came from there too (TIKI MANAGER) and so I didn't change it by putting something else, it could even be CYPHT_

**Comment by marclaporte** [comment]
> This is an option to take into consideration, however there is too much refactoring to do because this will affect all cypht modules, unit tests, lib and certain javascript files.

Is this for  `Hm_`, `TM_` or both?

Cypht 2.0 has not been released yet so almost no one is using TM_ yet. So it could make sense to do before we release 2.0: https://github.com/cypht-org/cypht/issues/966

**Comment by Shadow243** [comment]
> > This is an option to take into consideration, however there is too much refactoring to do because this will affect all cypht modules, unit tests, lib and certain javascript files.
> 
> 
> 
> Is this for  `Hm_`, `TM_` or both?
> 
> 
> 
> Cypht 2.0 has not been released yet so almost no one is using TM_ yet. So it could make sense to do before we release 2.0: https://github.com/cypht-org/cypht/issues/966 
> 
> 
> 
> 
> 
> 

Copy that @marclaporte

**Comment by marclaporte** [comment]
https://github.com/cypht-org/cypht/pull/967

**Comment by marclaporte** [comment]
So this task is partly done, and the rest is covered by https://github.com/cypht-org/cypht/issues/602
