### ISSUE TITLE
Page rendering, and settings issues

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#979]
### Version & Environment
[f198621](https://github.com/cypht-org/cypht/commit/f198621d8a0fb9dd8b01a872c694f65b1169057f)
Rev: []

OS:  Debian 12.5

### Steps to reproduce
1. Setup a brand-new Debian 12.5 installation
2. Install all available dependencies using "apt install -y php composer php-curl php-redis php-gd php-memcached php-gnupg php-imagick php-bcmath php-soap php-xdebug php-xml php-pgsql php-fpm php-tidy"
3. Setup Apache to use PHP with "sudo a2enmod proxy_fcgi setenvif" and "sudo a2enconf php8.2-fpm"
4. Use git to clone the master, extract it, then run "composer install" in the extracted folder.
5. Composer will list four optional components that are missing.  One can be installed easily, so run "composer require cerdic/css-tidy"
6. Prep the files for copying to /usr with the following commands:
"find cypht-master -type d -print | xargs chmod 755;find cypht-master -type f -print | xargs chmod 644"
7. su into root  (everything that happens below here is done as root, not with sudo)
8. Use chown -R to change ownership of the cypht folder to root.
9. Move the folder to /usr/local/share/cypht
10. Create the /var/lib/hm3, /var/lib/hm3/attachments, /var/lib/hm3/users, and /var/lib/hm3/app_data folders, and chown /var/lib/hm3 to "www-data" <-- a couple of these folders aren't required with my setup - more details on that later
11. Create a .env file to configure the app.
12. Once configured, link /usr/local/share/cypht to Apache's root folder.
13. Run php ./scripts/config_gen.php, and php ./scripts/create_account.php [user] [pass]
14. Visit the cypht site, and log in.

At this point for me, Cypht was having issues rendering the pages properly (as if the CSS wasn't completely being followed), the link to "Everything" in the menu was missing, and the drop-down to switch themes was missing.  I also notice that the example .env file is missing a number of modules that were listed there previously.  The missing modules that I noticed were history, saved_searches, advanced_search, highlights, profiles, inline_message, imap_folders, site, and recover_settings.  Not sure if those would affect things, but I tried logging into the site both with and without them, and had the same issues.

Am I missing, or mixing up some install steps, or are these actually bugs?

**Comment by Baraka24** [comment]
> ## 🐛 Bugreport

> Am I missing, or mixing up some install steps, or are these actually bugs?

Hello @PaulTGG, amazing that all your listed steps work fine  for cypht installation on a fresh debian 12.5. I and @IrAlfred  worked on this seriously, you did not miss any thing FYI..... We followed all steps as you provided up and everyting works fine. We recorded a video to show you  that the OS we are using is Debian 12.5 and testing page rendering as well as settings..... See from this short video: 

https://github.com/cypht-org/cypht/assets/81784141/11ef80e6-06c9-408b-9e65-d4df5f664063

Thanks @PaulTGG , We can assist you as well if  you need assistance.

**Comment by PaulTGG** [comment]
Thanks, I just tried again, and everything was rendering as expected.  (Not sure why I was having issues before, but there we are.)  That solves the rendering issues, but the link to "Everything" is still missing from my left-hand menu, and the example .env file is still missing an number of modules.  (Maybe the available modules are listed elsewhere?)

**Comment by Baraka24** [comment]
> Thanks, I just tried again, and everything was rendering as expected. (Not sure why I was having issues before, but there we are.) That solves the rendering issues, but the link to "Everything" is still missing from my left-hand menu, and the example .env file is still missing an number of modules. (Maybe the available modules are listed elsewhere?)

Eeeh Well, please see here about "Everyting" link https://github.com/cypht-org/cypht/pull/809 and  for modules in .env file if you want all enabled just update 194 Line of .env by adding the module you want. For e.g. `CYPHT_MODULES="core,contacts,local_contacts,carddav_contacts,profiles,imap_folders,ldap_contacts,gmail_contacts,feeds,jmap,imap,smtp,account,idle_timer,desktop_notifications,calendar,themes,nux,developer,sievefilters,api_login,recover_settings,hello_world,dynamic_login,inline_message,nasa,highlights,advanced_search,saved_searches,history,wordpress,recaptcha,github,tags,pgp,keyboard_shortcuts,site"
` We should may be add a comment up on 1954 and or the code provided here (which enables all modules but commented) to lead cypht users as well..... Isn't @marclaporte .

**Comment by PaulTGG** [comment]
I just tested with two email accounts, and "Everything" is still missing.  I'm still able to change the setting to show the Everything view on first log in.  The "All" view would be a good alternative, but I don't see "All" in the drop-down for "First page after login", and the "All" link is hidden by default.  (Screenshot shows all of the above.)
![Screenshot_2024-04-28_15-25-54](https://github.com/cypht-org/cypht/assets/12187131/7b711c79-fb2f-4780-896b-094246c73e78)

**Comment by Baraka24** [comment]
- [ ] "Everything" is still missing...... ouuuuf  ..... Oh yes. I have tested this too.....We'll fix. Thanks @PaulTGG .... 
 - [ ] "All" link is hidden by default as in Cypht 1.4.x

**Comment by marclaporte** [comment]
> We should may be add a comment up on 1954 and or the code provided here (which enables all modules but commented) to lead cypht users as well

@Shadow243 thoughts?

**Comment by Shadow243** [comment]
> > We should may be add a comment up on 1954 and or the code provided here (which enables all modules but commented) to lead cypht users as well
> 
> @Shadow243 thoughts?

Rather than adding a comment directly to the .env file to explain its purpose, I would recommend considering adding or improving comments in the configuration file itself, such as here: [https://github.com/cypht-org/cypht/blob/master/config/app.php#L682](https://github.com/cypht-org/cypht/blob/master/config/app.php#L682) 

Additionally, we could consider adding a dedicated section to the documentation, especially in version 2: [https://www.cypht.org/install-2x.html](https://www.cypht.org/install-2x.html)

**Comment by Shadow243** [comment]
> * [ ]  "Everything" is still missing...... ouuuuf  ..... Oh yes. I have tested this too.....We'll fix. Thanks @PaulTGG ....
> * [ ]  "All" link is hidden by default as in Cypht 1.4.x

I requested your review of it here [https://github.com/cypht-org/cypht/pull/984](https://github.com/cypht-org/cypht/pull/984)

**Comment by PaulTGG** [comment]
> Hello @PaulTGG . I hope this #984 fixes..... Now everything is visible. Thanks @Shadow243.

Looks like it's working now, thanks!
