### ISSUE TITLE
"Allow Images" link missing/hidden

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#985]
### Version & Environment

Rev: [57756bc](https://github.com/cypht-org/cypht/commit/57756bc36e1b965323732eec098cf732860b1db6)

OS:  Debian 12.5

### Steps to reproduce
1. Install latest master.
2. Look at an email that has images.
3. There's no link to allow images.

Issue https://github.com/cypht-org/cypht/pull/873 was designed to allow images from a particular sender, but if the link is there it isn't obvious where.

**Comment by marclaporte** [comment]
@jacob-js please advise :-)

**Comment by PaulTGG** [comment]
@jacob-js More info - the links are only missing from the inline view.  Both links (allow, and always allow) appear in the not-inline view.

**Comment by jacob-js** [comment]
> @jacob-js More info - the links are only missing from the inline view. Both links (allow, and always allow) appear in the not-inline view.

This could probably be the case. Let me give it a look.
Thanks @PaulTGG

**Comment by jacob-js** [comment]
@PaulTGG please help me! How do you toggle the inline view?

**Comment by PaulTGG** [comment]
@jacob-js I use these settings:
![setting](https://github.com/cypht-org/cypht/assets/12187131/7c579a9e-ba64-48ec-ad76-2a7f62ab44a1)

...and I open the email from the inbox by clicking on the subject line:
![inlineview](https://github.com/cypht-org/cypht/assets/12187131/089ce84c-e892-4a55-9a0c-d6c8bb9a7052)

**Comment by jacob-js** [comment]
@PaulTGG suprisingly I don't have such settings.
<img width="1108" alt="Screenshot Settings" src="https://github.com/cypht-org/cypht/assets/68013195/7f03dccb-b275-467f-a91f-2cf21e59663a">

I don't understand.
Is your version other than the latest master?

**Comment by PaulTGG** [comment]
@jacob-js I'm running the latest master: 492f634.  Also, I did not do an in-place upgrade.  I use a database, and my database didn't change, but the front-end cypht folder was completely rebuilt from scratch.

**Comment by PaulTGG** [comment]
@jacob-js Do you have the "inline_messages" module active in your .env file?  That module is missing from the .env.example file, so you'd have to add it manually.

**Comment by jacob-js** [comment]
> @jacob-js Do you have the "inline_messages" module active in your .env file? That module is missing from the .env.example file, so you'd have to add it manually.

Thank you! This one fixed.
I re-confirm the reported issue, let's fix...

**Comment by jacob-js** [comment]
Closing the issue, a PR has been created.
https://github.com/cypht-org/cypht/pull/1002
