### ISSUE TITLE
Deleting message from inline view shows multiple "message deleted" notifications

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#991]
## 🐛 Bugreport
Deleting message with the "delete" link while viewing the message inline shows multiple "message deleted" notifications.
![message deleted](https://github.com/cypht-org/cypht/assets/12187131/a37af50f-47fa-4088-9f2c-b8074962e096)

This doesn't happen when deleting a message from single-message view with the same link, and it doesn't happen from the mailbox view when using the checkboxes and the top delete button.

### Version & Environment

Rev: 492f634

OS:  Debian 12.5

**Comment by marclaporte** [comment]
@aggestor Please show us your skills :-)

**Comment by PaulTGG** [comment]
Not sure if it's related, but if you use the checkbox + delete button at the top of the page to delete a message that you're viewing inline, the message stays on screen until you open another item, or close it.  (The message line in the list of messages disappears, but the message itself does not automatically close.)  If it's not related, I'll open another but report for it later.

**Comment by Baraka24** [comment]
Hello @PaulTGG, Please is your instance up to date? My side I can not even see the dele message as we could..... You can see from: 

https://github.com/cypht-org/cypht/assets/81784141/b9fc0534-d823-4393-afdc-59ccf8e3ccac

Just confirm us that you are using the latest code on master or no. If no, try to put it up to date and test again.... If you get the same result as on this short video please tell us.... we'll likely to fix so the message will be visible. Thanks.

**Comment by marclaporte** [comment]
> Just confirm us that you are using the latest code on master or no.

He indicated above the revision he used.

**Comment by Baraka24** [comment]
> > Just confirm us that you are using the latest code on master or no.
> 
> He indicated above the revision he used.

Eeeh! well. I can see: 
> Not sure if it's related, but if you use the checkbox + delete button at the top of the page to delete a message that you're viewing inline, the message stays on screen until you open another item, or close it. (The message line in the list of messages disappears, but the message itself does not automatically close.) If it's not related, I'll open another but report for it later.

**Please @PaulTGG can you provide us some more details like a short video for example, I am not getting you well.**

**Comment by PaulTGG** [comment]
@Baraka24 Video is here!: https://dai.ly/kwLnThhImAx4wNAAml6

**Comment by PaulTGG** [comment]
@Baraka24 Were you able to view the video?

> @Baraka24 Video is here!: https://dai.ly/kwLnThhImAx4wNAAml6
> 
> (Looks like it's muted by default - click the video to unmute.)

**Comment by Baraka24** [comment]
> @Baraka24 Were you able to view the video?
> 
> > @Baraka24 Video is here!: https://dai.ly/kwLnThhImAx4wNAAml6
> > (Looks like it's muted by default - click the video to unmute.)

@PaulTGG Thanks, I have reproduced this on my local instance, I am working on it and I shall come back to you in a PR.

**Comment by marclaporte** [comment]
@Baraka24 I look forward to your next steps :-)

**Comment by Baraka24** [comment]
> @Baraka24 I look forward to your next steps :-)

It is being resolved here: [PR](https://github.com/cypht-org/cypht/pull/1106)

**Comment by PaulTGG** [comment]
Closed per #1106.
