### ISSUE TITLE
Possible issue with themes?

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#993]
## 🐛 Bugreport
I notice a lot of the themes have some strange anomalies.

Here's a screenshot of the Slate theme, showing the very bright gradients, and the strange whitespace on the left and lower-left:
![theme](https://github.com/cypht-org/cypht/assets/12187131/6897061f-065a-44c5-b4fc-2890bbaa12d7)

...and here's the Bootswatch demo of the Slate theme (showing, for example, way more subtle gradients): https://bootswatch.com/slate/

This is working as intended, or is there a way to more tightly integrate these themes?

### Version & Environment

Rev: 492f634

Related: https://github.com/cypht-org/cypht/pull/921

**Comment by marclaporte** [comment]
@tarasis Any chance you can fix this one?

Thanks!

**Comment by marclaporte** [comment]
@tarasis We would really appreciate your help!

**Comment by Joekarl757** [comment]
@PaulTGG I can reproduce this as it is working as expected on my side. I tested on 3 computers (mac, 2 windows) but got same result. See the picture below
![Capture](https://github.com/cypht-org/cypht/assets/80443697/f0ba6ee2-5b63-43f0-acac-367aef15efaf)

**Comment by PaulTGG** [comment]
@Joekarl757 I would hope that the OS wouldn't make as big a difference as the browser rendering engine, but I'm still seeing the issue using both Firefox and Chrome on Linux.  I also see you're using the Debug site, do you get the same result on the normal site?  This screenshot is from a fresh install of Cypht on a fresh Debian server.
![Screenshot_2024-06-06_12-46-10](https://github.com/cypht-org/cypht/assets/12187131/014c194e-b3f6-4f12-b55d-1b95a52b6c9c)

**Comment by PaulTGG** [comment]
Resolved in #1073.  Thanks @Joekarl757!
